# Copyright (c) 1999 bivio, LLC.  All rights reserved.
# $Id$
# Generated by ../generate.PL on Wed Aug 18  7:57:50 1999
# from tables.sql,v 1.13 1999/08/13 17:06:21 moeller Exp 
package Bivio::Biz::PropertyModel::ClubInstrumentEntry;
use strict;
$Bivio::Biz::PropertyModel::ClubInstrumentEntry::VERSION = sprintf('%d.%02d', q$Revision$ =~ /\d+/g);

=head1 NAME

Bivio::Biz::PropertyModel::ClubInstrumentEntry - interface to instrument_entry_t SQL table

=head1 SYNOPSIS

    use Bivio::Biz::PropertyModel::ClubInstrumentEntry;
    Bivio::Biz::PropertyModel::ClubInstrumentEntry->new($req);

=cut

=head1 EXTENDS

L<Bivio::Biz::PropertyModel>

=cut

use Bivio::Biz::PropertyModel;
@Bivio::Biz::PropertyModel::ClubInstrumentEntry::ISA = qw(Bivio::Biz::PropertyModel);

=head1 DESCRIPTION

C<Bivio::Biz::PropertyModel::ClubInstrumentEntry> is the create, read, update,
and delete interface to the C<instrument_entry_t> table.

=cut

#=IMPORTS
use Bivio::SQL::Constraint;
use Bivio::Type::Amount;
use Bivio::Type::Name;
use Bivio::Type::PrimaryId;

#=VARIABLES

=head1 METHODS

=cut

=for html <a name="internal_initialize"></a>

=head2 internal_initialize() : hash_ref

B<FOR INTERNAL USE ONLY>

=cut

sub internal_initialize {
    return {
	version => 1,
	table_name => 'club_instrument_entry_t',
	columns => {
            entry_id => ['Bivio::Type::PrimaryId',
    		Bivio::SQL::Constraint::PRIMARY_KEY()],
            club_instrument_id => ['Bivio::Type::PrimaryId',
    		Bivio::SQL::Constraint::NOT_NULL()],
            shares => ['Bivio::Type::Amount',
    		Bivio::SQL::Constraint::NOT_NULL()],
            block => ['Bivio::Type::Name',
    		Bivio::SQL::Constraint::NOT_NULL()],
        },
#TODO: SECURITY: Not authenticated, but ok to load other models?
	other => [
	    [qw(entry_id Entry.entry_id)],
	    [qw(club_instrument_id ClubInstrument.club_instrument_id)],
	],
    };
}

#=PRIVATE METHODS

=head1 COPYRIGHT

Copyright (c) 1999 bivio, LLC.  All rights reserved.

=head1 VERSION

$Id$

=cut

1;
