# Copyright (c) 1999 bivio, LLC.  All rights reserved.
# $Id$
# Generated by ../generate.PL on Wed Aug 18  7:57:50 1999
# from tables.sql,v 1.13 1999/08/13 17:06:21 moeller Exp 
package Bivio::Biz::PropertyModel::Instrument;
use strict;
$Bivio::Biz::PropertyModel::Instrument::VERSION = sprintf('%d.%02d', q$Revision$ =~ /\d+/g);

=head1 NAME

Bivio::Biz::PropertyModel::Instrument - interface to instrument_t SQL table

=head1 SYNOPSIS

    use Bivio::Biz::PropertyModel::Instrument;
    Bivio::Biz::PropertyModel::Instrument->new($req);

=cut

=head1 EXTENDS

L<Bivio::Biz::PropertyModel>

=cut

use Bivio::Biz::PropertyModel;
@Bivio::Biz::PropertyModel::Instrument::ISA = qw(Bivio::Biz::PropertyModel);

=head1 DESCRIPTION

C<Bivio::Biz::PropertyModel::Instrument> is the create, read, update,
and delete interface to the C<instrument_t> table.

=cut

#=IMPORTS
use Bivio::SQL::Constraint;
use Bivio::Type::Boolean;
use Bivio::Type::InstrumentType;
use Bivio::Type::Line;
use Bivio::Type::Name;
use Bivio::Type::PrimaryId;
use Bivio::Type::Text;
use Bivio::SQL::Support;

#=VARIABLES

=head1 METHODS

=cut

=for html <a name="internal_initialize"></a>

=head2 internal_initialize() : array_ref

=cut

sub internal_initialize {
    return Bivio::SQL::Support->new('instrument_t', {
        instrument_id => ['Bivio::Type::PrimaryId',
		Bivio::SQL::Constraint::PRIMARY_KEY()],
        club_id => ['Bivio::Type::PrimaryId',
		Bivio::SQL::Constraint::NOT_NULL()],
        name => ['Bivio::Type::Line',
		Bivio::SQL::Constraint::NOT_NULL()],
        ticker_symbol => ['Bivio::Type::Name',
		Bivio::SQL::Constraint::NONE()],
        exchange_name => ['Bivio::Type::Name',
		Bivio::SQL::Constraint::NONE()],
        account_number => ['Bivio::Type::Name',
		Bivio::SQL::Constraint::NONE()],
        instrument_type => ['Bivio::Type::InstrumentType',
		Bivio::SQL::Constraint::NOT_NULL()],
        fed_tax_free => ['Bivio::Type::Boolean',
		Bivio::SQL::Constraint::NOT_NULL()],
        average_cost_method => ['Bivio::Type::Boolean',
		Bivio::SQL::Constraint::NOT_NULL()],
        drp_plan => ['Bivio::Type::Boolean',
		Bivio::SQL::Constraint::NOT_NULL()],
        remark => ['Bivio::Type::Text',
		Bivio::SQL::Constraint::NONE()],
    });
}

#=PRIVATE METHODS

=head1 COPYRIGHT

Copyright (c) 1999 bivio, LLC.  All rights reserved.

=head1 VERSION

$Id$

=cut

1;
