# Copyright (c) 1999 bivio, LLC.  All rights reserved.
# $Id$
# Generated by ../generate.PL on Wed Aug 18  7:57:50 1999
# from tables.sql,v 1.13 1999/08/13 17:06:21 moeller Exp 
package Bivio::Biz::PropertyModel::Transaction;
use strict;
$Bivio::Biz::PropertyModel::Transaction::VERSION = sprintf('%d.%02d', q$Revision$ =~ /\d+/g);

=head1 NAME

Bivio::Biz::PropertyModel::Transaction - interface to transaction_t SQL table

=head1 SYNOPSIS

    use Bivio::Biz::PropertyModel::Transaction;
    Bivio::Biz::PropertyModel::Transaction->new($req);

=cut

=head1 EXTENDS

L<Bivio::Biz::PropertyModel>

=cut

use Bivio::Biz::PropertyModel;
@Bivio::Biz::PropertyModel::Transaction::ISA = qw(Bivio::Biz::PropertyModel);

=head1 DESCRIPTION

C<Bivio::Biz::PropertyModel::Transaction> is the create, read, update,
and delete interface to the C<transaction_t> table.

=cut

#=IMPORTS
use Bivio::SQL::Constraint;
use Bivio::Type::DateTime;
use Bivio::Type::Name;
use Bivio::Type::PrimaryId;
use Bivio::Type::SourceClass;
use Bivio::Type::Text;
use Bivio::SQL::Support;

#=VARIABLES

=head1 METHODS

=cut

=for html <a name="internal_initialize"></a>

=head2 internal_initialize() : array_ref

=cut

sub internal_initialize {
    return Bivio::SQL::Support->new('transaction_t', {
        transaction_id => ['Bivio::Type::PrimaryId',
		Bivio::SQL::Constraint::PRIMARY_KEY()],
        club_id => ['Bivio::Type::PrimaryId',
		Bivio::SQL::Constraint::NOT_NULL()],
        source_class => ['Bivio::Type::SourceClass',
		Bivio::SQL::Constraint::NOT_NULL()],
        dttm => ['Bivio::Type::DateTime',
		Bivio::SQL::Constraint::NOT_NULL()],
        user_id => ['Bivio::Type::PrimaryId',
		Bivio::SQL::Constraint::NOT_NULL()],
        remark => ['Bivio::Type::Text',
		Bivio::SQL::Constraint::NONE()],
        broker_code => ['Bivio::Type::Name',
		Bivio::SQL::Constraint::NONE()],
    });
}

#=PRIVATE METHODS

=head1 COPYRIGHT

Copyright (c) 1999 bivio, LLC.  All rights reserved.

=head1 VERSION

$Id$

=cut

1;
