#!perl -w
# Copyright (c) 2001 bivio Software Artisans Inc.  All Rights reserved.
# $Id$
use strict;

=head1 NAME

b-httpd - calls Bivio::Test::HTTPd

=head1 RELEASE SCOPE

bOP

=head1 SYNOPSIS

b-httpd [options] command [args...]
s-http-dispatcher [--config] [-n] [server-name]

=head1 DESCRIPTION

See L<Bivio::Test::HTTPd|Bivio::Test::HTTPd>

=head1 DESCRIPTION

B<s-http-dispatcher> is used to run C<httpd> in single user mode
with a dynamically created configuration file.

I<server-name> defaults to C<http>.

B<This is a bad example to copy.>

Logs are written to stdout.

=head1 OPTIONS

=over 4

=item -background

Execute in background (not -X) mode.  KeepAlives will be turned on.

=item -n

Don't execute, just show configuration file generated and
command invocation string.

=item --[server-name.]port=(number|name)

The port to use (required in config file or on command line).

=item --[server-name.]handler=package

The package name of the handler to use.  Defaults to
L<Bivio::Agent::HTTP::Dispatcher|Bivio::Agent::HTTP::Dispatcher>.

=back

=cut

#=IMPORTS
use Bivio::Test::HTTPd;

#=VARIABLES
Bivio::Test::HTTPd->main(@ARGV);

=head1 SEE ALSO

Bivio::Test::HTTPd

=head1 COPYRIGHT

Copyright (c) 2001 bivio Software Artisans Inc.  All Rights reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
