#!perl -w
# Copyright (c) 2002 bivio Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

b-testsuite - calls Bivio::Test::Engine

=head1 RELEASE SCOPE

Societas

=head1 SYNOPSIS

b-testsuite [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Test::Engine|Bivio::Test::Engine>

=cut

#=IMPORTS
use Bivio::Test::Engine;

#=VARIABLES
Bivio::Test::Engine->main(@ARGV);

=head1 SEE ALSO

Bivio::Test::Engine

=head1 COPYRIGHT

Copyright (c) 2002 bivio Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
