#!perl -w
# Copyright (c) 2001 bivio, LLC.  All rights reserved.
# $Id$
use strict;

=head1 NAME

b-petshop - calls Bivio::PetShop::Util

=head1 RELEASE SCOPE

bOP

=head1 SYNOPSIS

b-petshop [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::PetShop::Util|Bivio::PetShop::Util>

=cut

#=IMPORTS
use Bivio::PetShop::Util;

#=VARIABLES
Bivio::PetShop::Util->main(@ARGV);

=head1 SEE ALSO

Bivio::PetShop::Util

=head1 COPYRIGHT

Copyright (c) 2001 bivio, LLC.  All rights reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
