#!/bin/sh
#
# $Id$
#
# Manage servers for the Sociatas Application
#

RCDIR=/etc/rc.d/init.d

case "$1" in
  start)
	$RCDIR/b-file-server start
	$RCDIR/b-mail-dispatcher start
	$RCDIR/httpd start
	;;
  stop)
	$RCDIR/b-file-server stop
	$RCDIR/b-mail-dispatcher stop
	$RCDIR/httpd stop
	;;
  status)
	$RCDIR/b-file-server status
	$RCDIR/b-mail-dispatcher status
	$RCDIR/httpd status
	;;
  restart)
	$RCDIR/b-file-server restart
	$RCDIR/b-mail-dispatcher restart
	$RCDIR/httpd restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload|status}"
	echo "       Manage all Societas servers at once."
	exit 1
esac
exit 0
