#!perl -w
# Copyright (c) 1999 bivio, LLC.  All rights reserved.
# $Id$
use strict;

=head1 NAME

b-filtrum - filtrum utilities

=head1 SYNOPSIS

b-filtrum [options] command [args]

=head1 DESCRIPTION

see L<Bivio::Biz::Util::Filtrum|Bivio::Biz::Util::Filtrum>.

=cut

#=IMPORTS
use Bivio::Biz::Util::Filtrum;

#=VARIABLES

Bivio::Biz::Util::Filtrum->main(@ARGV);

=head1 SEE ALSO

Bivio::IO::Config

=head1 COPYRIGHT

Copyright (c) 1999 bivio, LLC.  All rights reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
