#!perl -w
# Copyright (c) 2002 bivio Software Artisans, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

b-iif - calls Bivio::Biz::Util::IIF

=head1 RELEASE SCOPE

Societas

=head1 SYNOPSIS

b-iif [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Biz::Util::IIF|Bivio::Biz::Util::IIF>

=cut

#=IMPORTS
use Bivio::Biz::Util::IIF;

#=VARIABLES
Bivio::Biz::Util::IIF->main(@ARGV);

=head1 SEE ALSO

Bivio::Biz::Util::IIF

=head1 COPYRIGHT

Copyright (c) 2002 bivio Software Artisans, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
