#!perl -w
# Copyright (c) 2001 bivio, LLC.  All rights reserved.
# $Id$
use strict;

=head1 NAME

b-investware - calls Bivio::Biz::Util::InvestWare

=head1 SYNOPSIS

b-investware [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Biz::Util::InvestWare|Bivio::Biz::Util::InvestWare>

=cut

#=IMPORTS
use Bivio::Biz::Util::InvestWare;

#=VARIABLES
Bivio::Biz::Util::InvestWare->main(@ARGV);

=head1 SEE ALSO

Bivio::Biz::Util::InvestWare

=head1 COPYRIGHT

Copyright (c) 2001 bivio, LLC.  All rights reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
