#!perl -w
# Copyright (c) 1999 bivio, LLC.  All rights reserved.
# $Id$
use strict;

=head1 NAME

b-list-model - ListModel utilities

=head1 SYNOPSIS

b-list-model [options] command [args]

=head1 DESCRIPTION

see L<Bivio::Biz::Util::ListModel|Bivio::Biz::Util::ListModel>.

=cut

#=IMPORTS
use Bivio::Biz::Util::ListModel;

#=VARIABLES

Bivio::Biz::Util::ListModel->main(@ARGV);

=head1 SEE ALSO

Bivio::IO::Config

=head1 COPYRIGHT

Copyright (c) 1999 bivio, LLC.  All rights reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
