#!perl -w
# Copyright (c) 1999 bivio, LLC.  All rights reserved.
# $Id$
use strict;

=head1 NAME

b-mail - manipulate mail_t database table

=head1 SYNOPSIS

b-mail [-n] [-migrate from-id to-id]

=head1 DESCRIPTION

see L<Bivio::Biz::Util::Mail|Bivio::Biz::Util::Mail>.

=cut

#=IMPORTS
use Bivio::Biz::Util::Mail;

#=VARIABLES

Bivio::Biz::Util::Mail->main(@ARGV);

=head1 SEE ALSO

Bivio::Biz::Model::Mail

=head1 COPYRIGHT

Copyright (c) 1999 bivio, LLC.  All rights reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
