#!perl -w
# Copyright (c) 1999 bivio, LLC.  All rights reserved.
# $Id$
use strict;

=head1 NAME

b-password-request - manipulate password_request_t database table

=head1 SYNOPSIS

  b-password-request [-n] -expire

=head1 DESCRIPTION

See L<Bivio::Biz::Util::PasswordRequest|Bivio::Biz::Util::PasswordRequest>.

=cut

#=IMPORTS
use Bivio::Biz::Util::PasswordRequest;

#=VARIABLES

#=PRIVATE METHODS

#=MAIN

Bivio::Biz::Util::PasswordRequest->main(@ARGV);

=head1 SEE ALSO

Bivio::Biz::Util::PasswordRequest

=head1 COPYRIGHT

Copyright (c) 1999 bivio, LLC.  All rights reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
