#!perl -w
# Copyright (c) 1999 bivio, LLC.  All rights reserved.
# $Id$
use strict;

=head1 NAME

b-user - manipulate user_t database table

=head1 SYNOPSIS

b-realm-owner [-n] -delete

=head1 DESCRIPTION

see L<Bivio::Biz::Util::User|Bivio::Biz::Util::User>.

=cut

#=IMPORTS
use Bivio::Biz::Util::User;

#=VARIABLES

Bivio::Biz::Util::User->main(@ARGV);

=head1 SEE ALSO

Bivio::IO::Config

=head1 COPYRIGHT

Copyright (c) 1999 bivio, LLC.  All rights reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
