# Copyright (c) 1999 bivio, LLC.  All rights reserved.
# $Id$
package Bivio::Type::DateTime;
use strict;
$Bivio::Type::DateTime::VERSION = sprintf('%d.%02d', q$Revision$ =~ /\d+/g);

=head1 NAME

Bivio::Type::DateTime - base class for all date/time types and type in itself

=head1 SYNOPSIS

    use Bivio::Type::DateTime;

=cut

=head1 EXTENDS

L<Bivio::Type>

=cut

use Bivio::Type;
@Bivio::Type::DateTime::ISA = qw(Bivio::Type);

=head1 DESCRIPTION

C<Bivio::Type::DateTime> is an absolute date, i.e. has both
clock and calendar components.  It is also the base class of
L<Bivio::Type::Date|Bivio::Type::Date>
and L<Bivio::Type::Time|Bivio::Type::Time>.
This allows for some common code.

Although a C<DateTime> is represented in perl as an int,
it is not a L<Bivio::Type::Number|Bivio::Type::Number>.

=cut

=head1 CONSTANTS

=cut

=for html <a name="SECONDS_IN_DAY"></a>

=head2 SECONDS_IN_DAY : int

Returns the number of seconds in a day

=cut

sub SECONDS_IN_DAY {
    return 86400;
}

=for html <a name="SQL_FORMAT"></a>

=head2 SQL_FORMAT : string

Returns 'J SSSSS'.

=cut

sub SQL_FORMAT {
    return 'J SSSSS';
}

=for html <a name="UNIX_EPOCH_IN_JULIAN_DAYS"></a>

=head2 UNIX_EPOCH_IN_JULIAN_DAYS : int

Number of days between the unix and julian epoch

=cut

sub UNIX_EPOCH_IN_JULIAN_DAYS {
    return 2440588;
}

=head1 METHODS

=cut

=for html <a name="from_literal"></a>

=head2 static from_literal(string value) : string

Makes sure is a unsigned number.

=cut

sub from_literal {
    my(undef, $value) = @_;
#TODO: Improve the checks here
    return $value =~ /^\d+$/ ? $value : undef;
}

=for html <a name="from_sql_column"></a>

=head2 from_sql_column(string result) : string

Converts the string in 'J SSSSS' form to a unix time (integer).

=cut

sub from_sql_column {
    my(undef, $result) = @_;
    return undef unless defined($result);
    my($j, $s) = split(/ /, $result);
    return ($j - UNIX_EPOCH_IN_JULIAN_DAYS()) * SECONDS_IN_DAY() + $s;
}

=for html <a name="from_sql_value"></a>

=head2 from_sql_value(string place_holder) : string

Returns C<TO_CHAR(I<place_holder>, 'J SSSSS')>.

=cut

sub from_sql_value {
    my(undef, $place_holder) = @_;
    return 'TO_CHAR('.$place_holder.",'".SQL_FORMAT()."')";
}

=for html <a name="get_width"></a>

=head2 static get_width : int

Returns 10.  This is the largest string representation of the maximum
perl integer (2^31).

=cut

sub get_width {
    return 10;
}

=for html <a name="to_sql_param"></a>

=head2 to_sql_param(string param_value) : string

Returns string form of unix time (integer) which is acceptable
to a positional parameter generated by L<to_sql_value|"to_sql_value">.

=cut

sub to_sql_param {
    my(undef, $param_value) = @_;
    return undef unless defined($param_value);
    my($s) = $param_value % SECONDS_IN_DAY();
    my($j) = int($param_value / SECONDS_IN_DAY())
	    + UNIX_EPOCH_IN_JULIAN_DAYS();
    return $j . ' ' . $s;
}

=for html <a name="to_sql_value"></a>

=head2 to_sql_value(string place_holder) : string

Returns C<TO_DATE(I<place_holder>, 'J SSSSS')>.

=cut

sub to_sql_value {
    my(undef, $place_holder) = @_;
    return 'TO_DATE('.$place_holder.",'".SQL_FORMAT()."')";
}

#=PRIVATE METHODS

=head1 COPYRIGHT

Copyright (c) 1999 bivio, LLC.  All rights reserved.

=head1 VERSION

$Id$

=cut

1;
