#!perl -w
# Copyright (c) 2008 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

b - calls any ShellUtil

=head1 SYNOPSIS

b simple-class [options] command [args...]

=head1 DESCRIPTION

Examples:

    b SQL create_test_db
    b RealmAdmin -r demo info

=cut

#=IMPORTS
use Bivio::ShellUtil;

#=VARIABLES
Bivio::ShellUtil->required_main(@ARGV);

=head1 SEE ALSO

Bivio::Util::

=head1 COPYRIGHT

Copyright (c) 2008 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
