#!perl -w
# Copyright (c) 2002 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

b-backup - calls Bivio::Util::Backup

=head1 RELEASE SCOPE

bOP

=head1 SYNOPSIS

b-backup [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Util::Backup|Bivio::Util::Backup>

=cut

#=IMPORTS
use Bivio::Util::Backup;

#=VARIABLES
Bivio::Util::Backup->main(@ARGV);

=head1 SEE ALSO

Bivio::Util::Backup

=head1 COPYRIGHT

Copyright (c) 2002 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
