#!perl -w
# Copyright (c) 2005 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

b-cli - calls Bivio::Util::CLI

=head1 SYNOPSIS

b-cli [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Util::CLI|Bivio::Util::CLI>

=cut

#=IMPORTS
use Bivio::Util::CLI;

#=VARIABLES
Bivio::Util::CLI->main(@ARGV);

=head1 SEE ALSO

Bivio::Util::CLI

=head1 COPYRIGHT

Copyright (c) 2005 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
