#!perl -w
# Copyright (c) 2006 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

b-class - calls Bivio::Util::Class

=head1 SYNOPSIS

b-class [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Util::Class|Bivio::Util::Class>

=cut

#=IMPORTS
use Bivio::Util::Class;

#=VARIABLES
Bivio::Util::Class->main(@ARGV);

=head1 SEE ALSO

Bivio::Util::Class

=head1 COPYRIGHT

Copyright (c) 2006 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
