#!perl -w
# Copyright (c) 2008 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

b-crm - calls Bivio::Util::CRM

=head1 SYNOPSIS

b-crm [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Util::CRM|Bivio::Util::CRM>

=cut

#=IMPORTS
use Bivio::Util::CRM;

#=VARIABLES
Bivio::Util::CRM->main(@ARGV);

=head1 SEE ALSO

Bivio::Util::CRM

=head1 COPYRIGHT

Copyright (c) 2008 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
