#!perl -w
# Copyright (c) 2006 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

b-darwin-config - calls Bivio::Util::DarwinConfig

=head1 SYNOPSIS

b-darwin-config [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Util::DarwinConfig|Bivio::Util::DarwinConfig>

=cut

#=IMPORTS
use Bivio::Util::DarwinConfig;

#=VARIABLES
Bivio::Util::DarwinConfig->main(@ARGV);

=head1 SEE ALSO

Bivio::Util::DarwinConfig

=head1 COPYRIGHT

Copyright (c) 2006 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
