#!perl -w
# Copyright (c) 2008 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

b-dev - calls Bivio::Util::Dev

=head1 SYNOPSIS

b-dev [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Util::Dev|Bivio::Util::Dev>

=cut

#=IMPORTS
use Bivio::Util::Dev;

#=VARIABLES
Bivio::Util::Dev->main(@ARGV);

=head1 SEE ALSO

Bivio::Util::Dev

=head1 COPYRIGHT

Copyright (c) 2008 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
