#!perl -w
# Copyright (c) 2001 bivio Software Artisans Inc.  All Rights reserved.
# $Id$
use strict;

=head1 NAME

b-docbook - calls Bivio::Util::DocBook

=head1 RELEASE SCOPE

bOP

=head1 SYNOPSIS

b-docbook [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Util::DocBook|Bivio::Util::DocBook>

=cut

#=IMPORTS
use Bivio::Util::DocBook;

#=VARIABLES
Bivio::Util::DocBook->main(@ARGV);

=head1 SEE ALSO

Bivio::Util::DocBook

=head1 COPYRIGHT

Copyright (c) 2001 bivio Software Artisans Inc.  All Rights reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
