#!perl -w
# Copyright (c) 2002 bivio Software Artisans, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

b-host - calls Bivio::Util::Host

=head1 RELEASE SCOPE

bOP

=head1 SYNOPSIS

b-host [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Util::Host|Bivio::Util::Host>

=cut

#=IMPORTS
use Bivio::Util::Host;

#=VARIABLES
Bivio::Util::Host->main(@ARGV);

=head1 SEE ALSO

Bivio::Util::Host

=head1 COPYRIGHT

Copyright (c) 2002 bivio Software Artisans, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
