#!perl -w
# Copyright (c) 2005 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

b-http-conf - calls Bivio::Util::HTTPConf

=head1 RELEASE SCOPE

bOP

=head1 SYNOPSIS

b-http-conf [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Util::HTTPConf|Bivio::Util::HTTPConf>

=cut

#=IMPORTS
use Bivio::Util::HTTPConf;

#=VARIABLES
Bivio::Util::HTTPConf->main(@ARGV);

=head1 SEE ALSO

Bivio::Util::HTTPConf

=head1 COPYRIGHT

Copyright (c) 2005 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
