#!perl -w
# Copyright (c) 2002 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

b-linux-config - calls Bivio::Util::LinuxConfig

=head1 RELEASE SCOPE

bOP

=head1 SYNOPSIS

b-linux-config [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Util::LinuxConfig|Bivio::Util::LinuxConfig>

=cut

#=IMPORTS
use Bivio::Util::LinuxConfig;

#=VARIABLES
Bivio::Util::LinuxConfig->main(@ARGV);

=head1 SEE ALSO

Bivio::Util::LinuxConfig

=head1 COPYRIGHT

Copyright (c) 2002 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
