#!/usr/bin/perl -w

eval 'exec /usr/bin/perl -w -S $0 ${1+"$@"}'
    if 0; # not running under some shell
# Copyright (c) 2001 bivio Inc.  All rights reserved.
# $Id$
use strict;

=head1 NAME

b-release - calls Bivio::Util::Release

=head1 RELEASE SCOPE

bOP

=head1 SYNOPSIS

b-release [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Util::Release|Bivio::Util::Release>

=cut

#=IMPORTS
use Bivio::Util::NewApp;

#=VARIABLES
Bivio::Util::NewApp->main(@ARGV);

=head1 SEE ALSO

Bivio::Util::NewApp

=head1 COPYRIGHT

Copyright (c) 2001 bivio Inc.  All rights reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
