#!perl -w
# Copyright (c) 2007 bivio Software Artisans, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

b-opie - calls Bivio::Util:OPIE'

=head1 RELEASE SCOPE

Artisans

=head1 SYNOPSIS

b-opie [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Util:OPIE|Bivio::Util:OPIE>

=cut

#=IMPORTS
use Bivio::ShellUtil;
use Bivio::Util::OPIE;

#=VARIABLES
Bivio::Util::OPIE->main(@ARGV);
#Bivio::ShellUtil->new('OPIE')->main(@ARGV);

=head1 SEE ALSO

Bivio::Util:OPIE

=head1 COPYRIGHT

Copyright (c) 2007 bivio Software Artisans, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
