#!perl -w
# Copyright (c) 2007 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

b-otp - calls Bivio::OTP::Util::OTP

=head1 SYNOPSIS

b-otp [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::OTP::Util::OTP|Bivio::OTP::Util::OTP>

=cut

#=IMPORTS
use Bivio::OTP::Util::OTP;

#=VARIABLES
Bivio::OTP::Util::OTP->main(@ARGV);

=head1 SEE ALSO

Bivio::OTP::Util::OTP

=head1 COPYRIGHT

Copyright (c) 2007 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
