#!perl -w
# Copyright (c) 2002 bivio Software Artisans, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

b-realm-admin - calls Bivio::Util::RealmAdmin

=head1 RELEASE SCOPE

bOP

=head1 SYNOPSIS

b-realm-admin [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Util::RealmAdmin|Bivio::Util::RealmAdmin>

=cut

#=IMPORTS
use Bivio::Util::RealmAdmin;

#=VARIABLES
Bivio::Util::RealmAdmin->main(@ARGV);

=head1 SEE ALSO

Bivio::Util::RealmAdmin

=head1 COPYRIGHT

Copyright (c) 2002 bivio Software Artisans, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
