#!perl -w
# Copyright (c) 2002 bivio Software Artisans, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

b-realm-file - calls Bivio::Util::RealmFile

=head1 RELEASE SCOPE

bOP

=head1 SYNOPSIS

b-realm-file [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Util::RealmFile|Bivio::Util::RealmFile>

=cut

#=IMPORTS
use Bivio::Util::RealmFile;

#=VARIABLES
Bivio::Util::RealmFile->main(@ARGV);

=head1 SEE ALSO

Bivio::Util::RealmFile

=head1 COPYRIGHT

Copyright (c) 2002 bivio Software Artisans, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
