#!perl -w
# Copyright (c) 2007 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

b-row-tag - calls Bivio::Util::RowTag

=head1 SYNOPSIS

b-row-tag [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Util::RowTag|Bivio::Util::RowTag>

=cut

#=IMPORTS
use Bivio::Util::RowTag;

#=VARIABLES
Bivio::Util::RowTag->main(@ARGV);

=head1 SEE ALSO

Bivio::Util::RowTag

=head1 COPYRIGHT

Copyright (c) 2007 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
