#!perl -w
# Copyright (c) 2006 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

b-search - calls Bivio::Util::Search

=head1 SYNOPSIS

b-search [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Util::Search|Bivio::Util::Search>

=cut

#=IMPORTS
use Bivio::Util::Search;

#=VARIABLES
Bivio::Util::Search->main(@ARGV);

=head1 SEE ALSO

Bivio::Util::Search

=head1 COPYRIGHT

Copyright (c) 2006 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
