#!perl -w
# Copyright (c) 2002 bivio Software Artisans, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

b-secret - calls Bivio::Util::Secret

=head1 RELEASE SCOPE

bOP

=head1 SYNOPSIS

b-secret [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Util::Secret|Bivio::Util::Secret>

=cut

#=IMPORTS
use Bivio::Util::Secret;

#=VARIABLES
Bivio::Util::Secret->main(@ARGV);

=head1 SEE ALSO

Bivio::Util::Secret

=head1 COPYRIGHT

Copyright (c) 2002 bivio Software Artisans, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
