#!perl -w
# Copyright (c) 2005 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

b-shell - calls Bivio::Util::Shell

=head1 SYNOPSIS

b-shell [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Util::Shell|Bivio::Util::Shell>

=cut

#=IMPORTS
use Bivio::Util::Shell;

#=VARIABLES
Bivio::Util::Shell->main(@ARGV);

=head1 SEE ALSO

Bivio::Util::Shell

=head1 COPYRIGHT

Copyright (c) 2005 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
