#!perl -w
# Copyright (c) 2007 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

b-site-forum - calls Bivio::Util::SiteForum

=head1 SYNOPSIS

b-site-forum [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Util::SiteForum|Bivio::Util::SiteForum>

=cut

#=IMPORTS
use Bivio::Util::SiteForum;

#=VARIABLES
Bivio::Util::SiteForum->main(@ARGV);

=head1 SEE ALSO

Bivio::Util::SiteForum

=head1 COPYRIGHT

Copyright (c) 2007 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
