#!perl -w
# Copyright (c) 2001 bivio, LLC.  All rights reserved.
# $Id$
use strict;

=head1 NAME

b-sql - calls Bivio::Util::SQL

=head1 RELEASE SCOPE

bOP

=head1 SYNOPSIS

b-sql [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Util::SQL|Bivio::Util::SQL>

=cut

#=IMPORTS
use Bivio::Util::SQL;

#=VARIABLES
Bivio::Util::SQL->main(@ARGV);

=head1 SEE ALSO

Bivio::Util::SQL

=head1 COPYRIGHT

Copyright (c) 2001 bivio, LLC.  All rights reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
