#!perl -w
# Copyright (c) 2007 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

b-test-user - calls Bivio::Util::TestUser

=head1 SYNOPSIS

b-test-user [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Util::TestUser|Bivio::Util::TestUser>

=cut

#=IMPORTS
use Bivio::Util::TestUser;

#=VARIABLES
Bivio::Util::TestUser->main(@ARGV);

=head1 SEE ALSO

Bivio::Util::TestUser

=head1 COPYRIGHT

Copyright (c) 2007 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
