#!perl -w
# Copyright (c) 2006 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

b-user - calls Bivio::Util::User

=head1 SYNOPSIS

b-user [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Util::User|Bivio::Util::User>

=cut

#=IMPORTS
use Bivio::Util::User;

#=VARIABLES
Bivio::Util::User->main(@ARGV);

=head1 SEE ALSO

Bivio::Util::User

=head1 COPYRIGHT

Copyright (c) 2006 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
