#!perl -w
# Copyright (c) 2007 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

b-wiki - calls Bivio::Util::Wiki

=head1 SYNOPSIS

b-wiki [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Util::Wiki|Bivio::Util::Wiki>

=cut

#=IMPORTS
use Bivio::Util::Wiki;

#=VARIABLES
Bivio::Util::Wiki->main(@ARGV);

=head1 SEE ALSO

Bivio::Util::Wiki

=head1 COPYRIGHT

Copyright (c) 2007 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
