#!/usr/bin/perl -w
# Copyright (c) 2008 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

bivio - calls any ShellUtil

=head1 SYNOPSIS

bivio simple-class [options] command [args...]

=head1 DESCRIPTION

Examples:

    bivio SQL create_test_db
    bivio RealmAdmin -r demo info

=cut

#=IMPORTS
use Bivio::IO::ClassLoader;

#=VARIABLES
Bivio::IO::ClassLoader->map_require('Bivio.ShellUtil')->required_main(@ARGV);

=head1 SEE ALSO

Bivio::ShellUtil

=head1 COPYRIGHT

Copyright (c) 2008 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
