#!perl -w
# Copyright (c) 2006 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

b-fptd - calls Bivio::Ext::NetFTPServer::Server

=head1 RELEASE SCOPE

bOP

=head1 SYNOPSIS

b-fptd [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::Ext::NetFTPServer::Server|Bivio::Ext::NetFTPServer::Server>

To run in background:
b-ftpd -S

To run in foreground:
b-ftpd -s

Uses the config file at /etc/ftpd.conf, ex.

port: 8022
allow anonymous: 1
error log: /var/log/ftpd.error
pidfile: /var/run/ftpd.pid
passive port range: 8000-8088
enable syslog: 0
daemon: 1

=cut

#=IMPORTS
use Bivio::Ext::NetFTPServer::Server;

#=VARIABLES
Bivio::Ext::NetFTPServer::Server->run;

=head1 SEE ALSO

Bivio::Ext::NetFTPServer::Server

=head1 COPYRIGHT

Copyright (c) 2006 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
