#!perl -w
# Copyright (c) 2008 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

pet-sql - calls Bivio::PetShop::Util::SQL

=head1 SYNOPSIS

pet-sql [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::PetShop::Util::SQL|Bivio::PetShop::Util::SQL>

=cut

#=IMPORTS
use Bivio::PetShop::Util::SQL;

#=VARIABLES
Bivio::PetShop::Util::SQL->main(@ARGV);

=head1 SEE ALSO

Bivio::PetShop::Util::SQL

=head1 COPYRIGHT

Copyright (c) 2008 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
