Date: Wed, 23 Feb 2000 23:11:55 -0700
From: Martin Lichtin <lichtin@bivio.com>
MIME-Version: 1.0
To: lichtin@bivio.com
Subject: test6
Content-Type: multipart/mixed;
 boundary="------------F385799F1182BDC18EA4C6E4"

This is a multi-part message in MIME format.
--------------F385799F1182BDC18EA4C6E4
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit

Big file attached!
--------------F385799F1182BDC18EA4C6E4
JVBERi0xLjINCiXi48/TDQoyIDAgb2JqDQo8PA0KL0QgWzEgMCBSIC9YWVogbnVsbCA2OTEg
X
MDBzKQ0KL0F1dGhvciAoRWRuYSBDIEVsbGUpDQovVGl0bGUgKDgxNWFyLmJvb2spDQovQ3Jl
