Return-Path: <lichtin@bivio.com>
Received: from bivio.com (pole.bivio.com [63.211.227.82])
	by pass.bivio.com (8.9.3/8.9.3) with ESMTP id TAA31471
	for <lichtin@mail.bivio.com>; Wed, 23 Feb 2000 19:55:54 -0700
Received: from pass.bivio.com (pass.bivio.com [207.174.140.78])
	by bivio.com (8.9.3/8.9.3) with ESMTP id TAA17367
	for <lichtin@bivio.com>; Wed, 23 Feb 2000 19:55:53 -0700
Received: from bivio.com (snow.bivio.com [207.174.140.70])
	by pass.bivio.com (8.9.3/8.9.3) with ESMTP id TAA31467
	for <lichtin@bivio.com>; Wed, 23 Feb 2000 19:55:53 -0700
Sender: lichtin@pass.bivio.com
Message-ID: <38B49DB9.3E9A7298@bivio.com>
Date: Wed, 23 Feb 2000 19:55:53 -0700
From: Martin Lichtin <lichtin@bivio.com>
Organization: bivio, LLC (http://www.bivio.com/)
X-Mailer: Mozilla 4.7 [en] (X11; U; Linux 2.2.13 i686)
X-Accept-Language: en
MIME-Version: 1.0
To: lichtin@bivio.com
Subject: test1
Content-Type: multipart/alternative;
 boundary="------------87A9D47A93B91C50AC533AD4"
X-Mozilla-Status: 8001
X-Mozilla-Status2: 00000000
X-UIDL: 38a24a7e000008ff


--------------87A9D47A93B91C50AC533AD4
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit

Have a pic [Image]  , don't be frightened.

--------------87A9D47A93B91C50AC533AD4
Content-Type: multipart/related;
 boundary="------------1D1B6D5E33E0906897B32F7D"


--------------1D1B6D5E33E0906897B32F7D
Content-Type: text/html; charset=us-ascii
Content-Transfer-Encoding: 7bit

<!doctype html public "-//w3c//dtd html 4.0 transitional//en">
<html>
Have a pic&nbsp;<a href="http://www.koerperwelten.com/"><img SRC="cid:part1.38B49DB9.1870C54B@bivio.com" height=144 width=113></a>
, don't be frightened.</html>

--------------1D1B6D5E33E0906897B32F7D
Content-Type: image/jpeg
Content-ID: <part1.38B49DB9.1870C54B@bivio.com>
Content-Transfer-Encoding: base64
Content-Disposition: inline; filename="/tmp/nsmail38B49DB928B0262.jpeg"

/9j/4AAQSkZJRgABAQAAAQABAAD//gB+RmlsZSB3cml0dGVuIGJ5IEFkb2JlIFBob3Rvc2hv
cKggNS4yCgpDUkVBVE9SOiBYViBWZXJzaW9uIDMuMTBhICBSZXY6IDEyLzI5Lzk0IChQTkcg
cGF0Y2ggMS4yKSAgUXVhbGl0eSA9IDc1LCBTbW9vdGhpbmcgPSAwCv/bAEMACAYGBwYFCAcH
BwkJCAoMFA0MCwsMGRITDxQdGh8eHRocHCAkLicgIiwjHBwoNyksMDE0NDQfJzk9ODI8LjM0
Mv/bAEMBCQkJDAsMGA0NGDIhHCEyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIy
MjIyMjIyMjIyMjIyMjIyMv/AABEIAJAAcQMBIgACEQEDEQH/xAAfAAABBQEBAQEBAQAAAAAA
AAAAAQIDBAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEU
MoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFla
Y2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPE
xcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/xAAfAQADAQEBAQEBAQEBAAAA
AAAAAQIDBAUGBwgJCgv/xAC1EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIy
gQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZ
WmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrC
w8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/APn+lAJp
yJnrUoAGRjtVKNwHRxKR15qyNqAK2COv1qLbnaw6D0pwIJxnjFdEdCSZhGST27VCSNrJt4zk
Gnfxc9KBjnHrxVPURJFDNfXEcNrE7zOcKqDJNek6N8F5J7JZdW1BoJpBkRW4DhR2yeh/Dj3r
iPDWmtrWtpp6zeQ8yN5cmcYccqM9skAfjXufhN7uLT7S0NzNckxBxJNj5ezKfowIweQa4sTV
adkb04Jq54R4n8K3/hXUjaXeHicboZlHyyD+hHcdv1rAYEnA+lfS3xH8NrrXhicJGHuYl8+I
gc71HIH1HFeR/Da2gGuC5n+zqchInuDgBuvy+rcY/OpVb92290NU7ysjg3R422ujKfRhg0hH
oe2a9t8egal4ckn1SyCyKW8m4LAFWHTGeSD3xxzXiXeilU543sFWk6cuVhtNNqyQjqC3yk+n
pUUqgPlRgVq42VzIjoooqQLMHC81Js5PqDTIgcfpVhRmQ/WumCuhMAOCBTdhUn0q7Fb+Y+Fr
tdD8CedGtxqgdA33IBwSPVj2+nWqrShRjzTYoJzdonAkbgKYUxzivUrjQ7S0gaOO1iVUzkgZ
LdutcR4gRLYkLHGjE9Frlhi41HZI1lScVe5Fp9u8sCQQIXuZ3yFXrgdAP1P5V33hfWr/AEi9
b7bcTBFAeYSvkbi3LZ9Cu057kk1yHh0mz1u0knG0R/eYjGM13N7bNrsNxZ2MyvNEqZkbg84Y
An2GOfeuXE1LysdGGh9pno1zr9jd6VFPZ3MNxHcELA6NnJJx/jn6V4ro19DpHiDUdOt4b0yi
dxFFAg7E7g2eeOn4Ve8Cafc2utLLvlRYJGYQ+YVC7sjdt6ZyMfhXW+JfD9odeXVrNI1vZJMu
c4WTHY+hI7/n6jK8Y8yeptSg3KLRgaj4rj0dIbq90t5o2YqoZgSHALAgHIGSdpx25615BcMJ
ZnlCBA7Fti9Bz0Fe0a94Zg1eGBL6WdREGMbREZyfXP0/SvNvEXhxNHeN4LjzoZCVIIwyHHQ9
jW2GnBq3VixeHqXdRK8TnV+6fbtUiBGTDk9zTCCBxTC3pXZex54uxf79FNx70VN/IC9AOOeu
atwx7n6VFboOp5rQt4yxRIky7MOAOSewr0aMNrmU5W2O8+HPhhb+RtUuY8xRttgX1b1/CvQt
QtFs4Rk5IHfoTVTQZhpFjDpttA0z2ygSOBtTdjnBPU/SqXiTxJ9nTZPA0MrkiPkEcdf0P618
zia8sRVcvu9D0qdPkikY966bp1ndS+3gDA2nNeZ6uGvtZitlU8vzjrjufyrqoGuLkz3kikW5
QhSe/wA3/wBauY0y/tLbWru+vS+2JCsaom4lyf8AAGuihHlTZnVaclE2NXtQdXg8pi0YhRjx
zyW/wrf8H79P16+hmUkOMse2OMfpisWz8/ULa6u5CokURnavG1NuR/PNdNb5Op3Ur92VQQvP
Ma9u/Ws6j93lOiG7Y+58UWuk6jPHNEu2Rx5Eix84XBw3ryxwfT8KbL4gGrqqRHCI2/dtxjjp
WXBDp2u69JZ3LEAzlI/mA+YfKB9DitPSfDK/2zfaSpaIwzHYc8gMAwHocbvx+tZ2VvM7KDjG
opS2Wptjbe6ZaebI+WiYHjuGIB/QVwPiS1e5truNUO6CMTMfYEgfoD+Fej3mgXlrpf8Ao0wc
2qkPhT8/Oe3Tqema8xtdUkOr3iXK7/PYp83YcDH5AfrWlGnNXqL7NjadenUj7KL+JtfmcGVY
swB4HWo2XBxWrqFi1pcyROu0A/L7gjIP4jBqg6lQc+vNerKGlz51qzsyDFFP20VFhGnENqg8
EdMVpWsotrmGRxko4bGfQ57VRhX92N34D1Ndt4E0mPUdXN1NGrQWYEhLjILk/KMfmfwr0ZSj
SoynPZIws5SSR6ek9vpnkyXl0IFdQWZup46c1jeLrSLxBok81vuMsDZgdoym49T16jA/lXTi
S3uyZI3QyRgK3+z0/wABVK/vYp7RHjiklG/aAB1OOntXxqlbVbnt2u9TzPS7k3Xgd0bCyRPI
hyOVOc/zP6Vyuh2cN6l7DPCHkB3IxJGM9e/0rtL2FbWwvT9njWZ2ZsKM5yeQPoD1rz+wvTaa
tI8ZwJEZfxI/xr1KPvQlY5XaNRXOn8KEC2aN23F1AdevGMD9K7bQbqPfKs8ZUxlcN+GP8K4b
wZCrTzOx4CcZ6cV3Fk8kcZSWEBgwYlScg8f4isa3xM3pK8Ty/VPtFjrL+Qu12uG2g9ucjmvU
/CN3c6neXmoziFriUpuRgAr8YIwfpXPeMNOS70/TLuBh5sc21lxhvmGB+RH610nhuCzk0xUa
SW1k81iJVT7xH6UpzvFG8Y8tObfkjpNTvmt9KuHWIKmxtzkEKo9M9/1rw5xHJqJnZiq+bvyv
X72a9L8VXDN4e8syqpm48odRz1P1A/8A115m67Sa9rKKCqU5t9dDx8ZVdNwS73+4teJ7Pz4L
S+VcbgYyAOMAKw/RwPwrlJogI+nOfyruNTEsng6OdAzRJc/eA4G9DkH33I34AVxUjbQRjcM8
GqoRSoqMt1dfia4mXPWc1s7Mp+WaKk8w+gopWiZE8U+5VB6iuk0XxLe6TaTW1rcGJJnV2wqk
5HpkH+VcnC2MYHHrV+EOTkNtIIP41tFKrHlmroh3i7p2Pc0s7mz0ptRhmD301sD9mxkKxAOW
xjoc9Md6Fto9NtLTzZgZZX3SnovPG73OePz9KxfC/wDaN9p8VzFcRyQ4KSq6lQGAGQcNj3zj
0qLWnltL5JGT7Sit5USEs2zJycjPcd/wr5SdO1Rweh7MX7qadyv4wWy2xQrHLGYVKs6w8yEE
4xnj/az715aqImpMi7iD03cdeK9K8UPf22nJbPNMrgbmQyEsg5G1uff8fzry+Vytyz9+xr0s
JscWI0dzvPC8ez7PsYAkPv8AXBplre3NpqM1tbuPLjlEaA5wx39CR6kYzTvDTK0qbt2VVeF7
HJ6/hiqOpPKgkjZUVZGfJA5J3luvryBV0aPtq3I2Odb2cOY6Ke7g8pL23dZdjyMyFslmjJOT
+G8/lXQWOrtNaeZGp5yjR4G4N/8Aq/nXnWkR+XGIwDh5JF+qGNlP5Z/Wuh0GaebSLi6jZgyY
kyAOeIwc/QEn8K5qtPlk49jsj+8pKfc3dbeCfTphcD/S9jSqqYwo6ZY9zgGvPJiMnmup1eWR
VvpCoRg3ksF6ZHDfqxrknIJBPSvfyX+BJ+f6I8fNIctSC/u3+9s6m5uLOL4XfY4YyJpJ45ZX
kb7zlnA2jPQKn6155dFQMgdRnitW91DfaW9rGxKxszEsc8nt9B1/E1jSsMknoKOXkjJPdtsH
Lmat0SK24+ooowv94/nRXPqUOiI24q9Gygg/NispH+XAq7G+ADmtKMyZK56t8LLtWj1W1b5s
bJVUnpnIJ/8AQa09b1m0sHZ9m6T+DZyxIzjH0ryC1uZIZd0cjRvjAZTgitS1vZkuYpTK7MGG
Cxz+HNc1bLFiKrq81r9DWGK9lDltc29Tu7zWbJ9Qumcqx2rGG+dQDyevf+VcXchmvV3xiN3Y
EoBgD1/rXc3cSIJAsmYgwZVVx8wwcAj+tcfr8kpvlnZxvI5x0B71zUoODsa1ZKVmdV4UR7pZ
WUDjaqsPXk81o+K4YDEHiVAqycbOgzn+dYOlaytnol3YCHy7orvAxj6n8j+lZc2qzSQrE0hK
L0H5/wCJrowlCTqqrfRMivJcnJ3RahuTbzxYJCo279QT+malg1O50lZ4IstDc201sV/uknhu
npiqNj/ptykGcGT5PxOMfyq/rMP9nSTxsMNDNwD7gZ/nWOJSVeS7u534a0sMk+n6GldX0k+j
oZsl5f3kh9y2a5u4cjOD+FbGoSPHpG3BEeUUE/T/AOsa5xnDA5bknvXflsuWg13b/Q5Mzjev
Hyil+LIJXzxnmqrbi2MZ5qWTKs6qvJOATVcyEdR9D6UVJa6nKiXcPUflRUPnj0oqOdAQocVY
WQ8VVqTPFZRlYZZjkOe+f6VcS5wy+o5rOjDAZ7VISQW7d63hUcUS0mbEmp3DHKyE8daozMbj
/WMT+NV1bn5SemakZgseFHJp2jLVoNdjo4NQs5JUM8f7wqAWAGfesV8IXQqchiMGq4lC7QFG
4HPPOakLGN1bhieTSpQUJNrYuc+aKT6FzTZDFqUTBcbTn+o/lXR+Mru1v9StryD5fOiUzL1G
4bf6AVzWmOz6nFzgswAra8QxFNXt7cJsVFVm46kjn8tv61x4mzrXOig2oOwut3DL4asw3Pnz
uw+YdFA7fj1+tcoWycnrUl5ciW5Yq+Y1JCg+n+eaqM3OR0Nb0V7OmkZVpupNyY53OTx05qF2
3dBT3k3R4xz3qItjgUTZmJtopuTRWd0AlPU4plKBmhASiTjBPFKHJc89eKZsIOGBH4Uuxs85
x2NVdgSI5UY6EUu89iaQqgO4FtvfIpjccD6VV2gH7uRTlmYHg8VFk+lFHM0Bfs7nbMGU7XUh
lx6g103iu93rHfJtDTQKhI9TkZH/AHya4uNtsyMTwGBNejR+HxrHgiQbGa+ijV4P9oKzZA9c
qx/KuatJKSkzopP3GluecnaxIVsDHf1pBwpzyKZtIJHp6Ulb3OcUk0h6UZNGTj2qQG0UUUgC
lBwaSigC5HJGVw4B9880EjzFKnb+tVFbBzVhVR3BJIUCtVK+grDy+cqWDcdaj38bSACKeQgG
ACajbaSGC/UU3cBSQMYyBSDbjvQQpUjbz25pNvHPSpGO+UHPOK9Tt/ELaB4ct7lkO3cI8Jhm
QYznBx/EAOvQ15WVU9Dg1vN4mv5dOks5YYJI2jKb9mCM8Z64/wDr49KxrUnUsuhpTnyXZnax
dwahrF1dwRCCGaQsiADj6479/wAao7BnG79KGUqOaaW7VrZJWM276htHPzUxuvWlz6U2pYBR
RRSA/9k=
--------------1D1B6D5E33E0906897B32F7D--

--------------87A9D47A93B91C50AC533AD4--
