# Copyright (c) 1999 bivio, LLC.  All rights reserved.
# $Id$
# Generated by ../generate.PL on Wed Aug 18  7:57:50 1999
# from tables.sql,v 1.13 1999/08/13 17:06:21 moeller Exp 
package Bivio::Biz::Model::Entry;
use strict;
$Bivio::Biz::Model::Entry::VERSION = sprintf('%d.%02d', q$Revision$ =~ /\d+/g);

=head1 NAME

Bivio::Biz::Model::Entry - interface to entry_t SQL table

=head1 SYNOPSIS

    use Bivio::Biz::Model::Entry;
    Bivio::Biz::Model::Entry->new($req);

=cut

=head1 EXTENDS

L<Bivio::Biz::PropertyModel>

=cut

use Bivio::Biz::PropertyModel;
@Bivio::Biz::Model::Entry::ISA = qw(Bivio::Biz::PropertyModel);

=head1 DESCRIPTION

C<Bivio::Biz::Model::Entry> is the create, read, update,
and delete interface to the C<entry_t> table.

=cut

#=IMPORTS
use Bivio::SQL::Constraint;
use Bivio::Type::Amount;
use Bivio::Type::EntryClass;
use Bivio::Type::EntryType;
use Bivio::Type::PrimaryId;
use Bivio::Type::TaxCategory;
use Bivio::Type::Text;

#=VARIABLES

=head1 METHODS

=cut

=for html <a name="internal_initialize"></a>

=head2 internal_initialize() : hash_ref

B<FOR INTERNAL USE ONLY>

=cut

sub internal_initialize {
    return {
	version => 1,
	table_name => 'entry_t',
	columns => {
            entry_id => ['Bivio::Type::PrimaryId',
    		Bivio::SQL::Constraint::PRIMARY_KEY()],
            realm_id => ['Bivio::Type::PrimaryId',
    		Bivio::SQL::Constraint::NOT_NULL()],
            realm_transaction_id => ['Bivio::Type::PrimaryId',
    		Bivio::SQL::Constraint::NOT_NULL()],
            class => ['Bivio::Type::EntryClass',
    		Bivio::SQL::Constraint::NOT_NULL()],
            entry_type => ['Bivio::Type::EntryType',
    		Bivio::SQL::Constraint::NOT_NULL()],
            tax_category => ['Bivio::Type::TaxCategory',
    		Bivio::SQL::Constraint::NOT_NULL()],
	    tax_basis => ['Bivio::Type::Boolean',
    		Bivio::SQL::Constraint::NOT_NULL()],
            amount => ['Bivio::Type::Amount',
    		Bivio::SQL::Constraint::NOT_NULL()],
#            remark => ['Bivio::Type::Text',
#    		Bivio::SQL::Constraint::NONE()],
        },
	other => [
#TODO: causes Deep recursion die
#	    [qw(entry_id RealmAccountEntry.entry_id
#                RealmInstrumentEntry.entry_id
#		MemberEntry.entry_id)],
	    [qw(realm_transaction_id RealmTransaction.realm_transaction_id)],
	],
	auth_id => 'realm_id',
    };
}

#=PRIVATE METHODS

=head1 COPYRIGHT

Copyright (c) 1999 bivio, LLC.  All rights reserved.

=head1 VERSION

$Id$

=cut

1;
