# Copyright (c) 1999 bivio, LLC.  All rights reserved.
# $Id$
# Generated by ../generate.PL on Wed Aug 18  7:57:50 1999
# from tables.sql,v 1.13 1999/08/13 17:06:21 moeller Exp 
package Bivio::Biz::Model::RealmInstrumentValuation;
use strict;
$Bivio::Biz::Model::RealmInstrumentValuation::VERSION = sprintf('%d.%02d', q$Revision$ =~ /\d+/g);

=head1 NAME

Bivio::Biz::Model::RealmInstrumentValuation - interface to realm_instrument_valuation_t SQL table

=head1 SYNOPSIS

    use Bivio::Biz::Model::RealmInstrumentValuation;
    Bivio::Biz::Model::RealmInstrumentValuation->new($req);

=cut

=head1 EXTENDS

L<Bivio::Biz::PropertyModel>

=cut

use Bivio::Biz::PropertyModel;
@Bivio::Biz::Model::RealmInstrumentValuation::ISA = qw(Bivio::Biz::PropertyModel);

=head1 DESCRIPTION

C<Bivio::Biz::Model::RealmInstrumentValuation> is the create, read, update,
and delete interface to the C<realm_instrument_valuation_t> table.

=cut

#=IMPORTS
use Bivio::Agent::Request;
use Bivio::SQL::Constraint;
use Bivio::Type::Amount;
use Bivio::Type::DateTime;
use Bivio::Type::PrimaryId;

#=VARIABLES

=head1 METHODS

=cut

=for html <a name="create_or_update"></a>

=head2 static Bivio::Biz::Model::RealmInstrumentValuation create_or_update(string realm_instrument_id, string date, string price)

Creates or updates an instance of RealmInstrumentValuation using the specifed
values.

=cut

sub create_or_update {
    my(undef, $realm_instrument_id, $date, $price) = @_;

    my($req) = Bivio::Agent::Request->get_current;
    my($inst_val) = Bivio::Biz::Model::RealmInstrumentValuation->new($req);

    # see if a valuation already exists, if so update it
    if ($inst_val->unsafe_load(
	    realm_instrument_id => $realm_instrument_id,
	    date_time => $date)) {

	$inst_val->update({price_per_share => $price});
    }
    else {
	$inst_val->create({
	    realm_id => $req->get('auth_id'),
	    realm_instrument_id => $realm_instrument_id,
	    date_time => $date,
	    price_per_share => $price,
	});
    }
    return $inst_val;
}

=for html <a name="internal_initialize"></a>

=head2 internal_initialize() : hash_ref

B<FOR INTERNAL USE ONLY>

=cut

sub internal_initialize {
    return {
	version => 1,
	table_name => 'realm_instrument_valuation_t',
	columns => {
            realm_instrument_id => ['Bivio::Type::PrimaryId',
    		Bivio::SQL::Constraint::PRIMARY_KEY()],
            realm_id => ['Bivio::Type::PrimaryId',
    		Bivio::SQL::Constraint::NOT_NULL()],
            date_time => ['Bivio::Type::DateTime',
    		Bivio::SQL::Constraint::PRIMARY_KEY()],
            price_per_share => ['Bivio::Type::Amount',
    		Bivio::SQL::Constraint::NOT_NULL()],
        },
#TODO: SECURITY: Not authenticated, but ok to load other models?
	other => [
	    [qw(realm_instrument_id RealmInstrument.realm_instrument_id)],
	],
    };
}

#=PRIVATE METHODS

=head1 COPYRIGHT

Copyright (c) 1999 bivio, LLC.  All rights reserved.

=head1 VERSION

$Id$

=cut

1;
