# Copyright (c) 1999 bivio, LLC.  All rights reserved.
# $Id$
# Generated by ../generate.PL on Wed Aug 18  7:57:50 1999
# from tables.sql,v 1.13 1999/08/13 17:06:21 moeller Exp 
package Bivio::Biz::Model::RealmInstrumentValuation;
use strict;
$Bivio::Biz::Model::RealmInstrumentValuation::VERSION = sprintf('%d.%02d', q$Revision$ =~ /\d+/g);
$_ = $Bivio::Biz::Model::RealmInstrumentValuation::VERSION;

=head1 NAME

Bivio::Biz::Model::RealmInstrumentValuation - interface to realm_instrument_valuation_t SQL table

=head1 SYNOPSIS

    use Bivio::Biz::Model::RealmInstrumentValuation;
    Bivio::Biz::Model::RealmInstrumentValuation->new($req);

=cut

=head1 EXTENDS

L<Bivio::Biz::PropertyModel>

=cut

use Bivio::Biz::PropertyModel;
@Bivio::Biz::Model::RealmInstrumentValuation::ISA = qw(Bivio::Biz::PropertyModel);

=head1 DESCRIPTION

C<Bivio::Biz::Model::RealmInstrumentValuation> is the create, read, update,
and delete interface to the C<realm_instrument_valuation_t> table.

=cut

#=IMPORTS
use Bivio::Agent::Request;

#=VARIABLES

=head1 METHODS

=cut

=for html <a name="create_or_update"></a>

=head2 static Bivio::Biz::Model::RealmInstrumentValuation create_or_update(string realm_instrument_id, string date, string price)

Creates or updates an instance of RealmInstrumentValuation using the specifed
values.

=cut

sub create_or_update {
    my($self, $realm_instrument_id, $date, $price) = @_;
    my($req) = Bivio::Agent::Request->get_current;

    unless (ref($self)) {
	$self = Bivio::Biz::Model::RealmInstrumentValuation->new($req);
    }

    # see if a valuation already exists, if so update it
    if ($self->unsafe_load(
	    realm_instrument_id => $realm_instrument_id,
	    date_time => $date)) {

	$self->update({price_per_share => $price});
    }
    else {
	$self->create({
	    realm_id => $req->get('auth_id'),
	    realm_instrument_id => $realm_instrument_id,
	    date_time => $date,
	    price_per_share => $price,
	});
    }
    return $self;
}

=for html <a name="internal_initialize"></a>

=head2 internal_initialize() : hash_ref

B<FOR INTERNAL USE ONLY>

=cut

sub internal_initialize {
    return {
	version => 1,
	table_name => 'realm_instrument_valuation_t',
	columns => {
            realm_instrument_id => ['RealmInstrument.realm_instrument_id',
		'PRIMARY_KEY'],
            realm_id => ['RealmOwner.realm_id', 'NOT_NULL'],
            date_time => ['DateTime', 'PRIMARY_KEY'],
            price_per_share => ['Amount', 'NOT_NULL'],
        },
	other => [
	    [qw(realm_instrument_id RealmInstrument.realm_instrument_id)],
	],
	auth_id => 'realm_id',
    };
}

#=PRIVATE METHODS

=head1 COPYRIGHT

Copyright (c) 1999 bivio, LLC.  All rights reserved.

=head1 VERSION

$Id$

=cut

1;
