# Copyright (c) 1999 bivio, LLC.  All rights reserved.
# $Id$
package Bivio::Agent::TaskId;
use strict;
$Bivio::Agent::TaskId::VERSION = sprintf('%d.%02d', q$Revision$ =~ /\d+/g);
$_ = $Bivio::Agent::TaskId::VERSION;

=head1 NAME

Bivio::Agent::TaskId - enum of identifying all Societas tasks

=head1 SYNOPSIS

    use Bivio::Agent::TaskId;

=cut

=head1 EXTENDS

L<Bivio::Type::Enum>

=cut

use Bivio::Type::Enum;
@Bivio::Agent::TaskId::ISA = ('Bivio::Type::Enum');

=head1 DESCRIPTION

C<Bivio::Agent::TaskId> defines all possible "tasks" within the Societas.  A
structure of a task is defined in L<Bivio::Agent::TaskBivio::Agent::Task>.

The syntax of the configuration table is defined as follows:

Always start enums at 1, so 0 can be reserved for UNKNOWN.
DO NOT CHANGE the numbers in this list, the values may be
stored in the database.

URLs can be aliases, separated by a colon (:).  However, the first
one is returned on get from task id.  See
L<Bivio::Agent::HTTP::Location|Bivio::Agent::HTTP::Location>.

URI components should use dashes (-), not underscores (_), to
make the component more readable.  Underscores disappear when
underlined.

A URI which contains a '?', will have a realm owner name in that
position.

A URI which contains a trailing '*', may have path_info.  These
URIs are severely restricted.  They cannot be set on the GENERAL
realm. They must be exactly /?/I<component>. I<component> must be
unique in the global URI space. All of these rules are checked in
L<Bivio::Agent::HTTP::Location|Bivio::Agent::HTTP::Location>.

Use '!' to mean "no uri".

B<Make  the following paragraph true.  We should tag tasks this way so we
have an idea of the tasks which need to be secure, but right
now user decides.>

LOGIN privileges mean something special.  It means the task
must be executed from an encrypted context.  Only tasks which
require the user to enter sensitive information, e.g. passwords,
credit cards, should have LOGIN set.

ACHTUNG: Any static top level URI names, must be in
Bivio::Type::RealmName::_RESERVED list.  In general, avoid top
level names, use C</pub/> names instead.

C<TaskId>s are defined "OBJECT_VERB", so they sort nicely.  The list of
tasks defined in this module is:

=over 4

=back

=cut

#=IMPORTS

#=VARIABLES
my(@_CFG) = (
#TODO: 9/13/00: Changed the last of the "_" URLs.  Should have done this
#      earlier.  Remove the aliases some time in the future(?).
    # Task used by Bivio::ShellUtil
    [qw(
        SHELL_UTIL
        1
        GENERAL
        DOCUMENT_READ
        !
        Bivio::Biz::Action::HTTPDocument
    )],
#    [qw(
#        TEST_JOB
#        2
#        CLUB
#        ACCOUNTING_WRITE&MEMBER_WRITE
#        ?/test_job
#        Bivio::Biz::Model::Lock
#        Bivio::Biz::Action::TestJob
#    )],
    # This is the DOCUMENT_TASK.  See Bivio::HTTP::Agent::Location
    [qw(
	HTTP_DOCUMENT
	3
        GENERAL
        DOCUMENT_READ
        /*
	Bivio::Biz::Action::HTTPDocument
        want_query=0
    )],
#TODO: MY_CLUB_SITE isn't right if user not part of club.
#      Need a redirect to club or to user's home.
    [qw(
	MY_CLUB_SITE
	4
        GENERAL
        ANY_USER
        my-club-site/*:pub/my_club_site
        Bivio::Biz::Action::MyRedirect->execute_club_site
        next=CLUB_INTRO
        want_query=0
    )],
    [qw(
	LOGIN
	5
        GENERAL
        LOGIN
        pub/login
	Bivio::Biz::Action::Logout
	Bivio::Biz::Model::LoginForm
	Bivio::UI::HTML::General::Login
        next=MY_CLUB_SITE
    )],
    # Must match the start of the tour
    [qw(
        TOUR
        6
        GENERAL
        DOCUMENT_READ
        hm/tour_new/index.html
        Bivio::Biz::Action::HTTPDocument
    )],
    [qw(
        ABOUT_US
        7
        GENERAL
        DOCUMENT_READ
        hm/about.html
        Bivio::Biz::Action::HTTPDocument
    )],
    [qw(
	LOGOUT
	8
        GENERAL
        DOCUMENT_READ
        pub/logout
        Bivio::Biz::Model::RealmInvite->execute_delete_cookie
	Bivio::Biz::Action::Logout
        Bivio::Biz::Action::ClientRedirect->execute_next
        next=HTTP_DOCUMENT
    )],
    [qw(
        CLUB_ACCOUNTING_ACCOUNT_LIST
        9
        CLUB
        ACCOUNTING_READ&ACCOUNT_READ
        ?/accounting/accounts:?/accounts
        Bivio::Biz::Action::ReportDate
        Bivio::Biz::Model::AccountSummaryList->execute_load_valuation_only
        Bivio::Biz::Model::OffBookAccountSummaryList->execute_load_non_valuation_only
        Bivio::UI::HTML::Club::AccountList
        next=CLUB_ACCOUNTING_ACCOUNT_LIST
        help=account-summary
        want_query=0
    )],
#10
    [qw(
        CLUB_ACCOUNTING_INVESTMENT_LIST
        11
        CLUB
        ACCOUNTING_READ&INVESTMENT_READ
        ?/accounting/investments:?/investments
        Bivio::Biz::Model::Lock
        Bivio::Biz::Action::ReportDate
        Bivio::Biz::Model::InstrumentSummaryList->execute_load_all
        Bivio::UI::HTML::Club::InstrumentList
        next=CLUB_ACCOUNTING_INVESTMENT_LIST
        help=investment-summary
        want_query=0
    )],
    [qw(
        CLUB_ACCOUNTING_MEMBER_LIST
        12
        CLUB
        ACCOUNTING_READ&MEMBER_READ
        ?/accounting/members
        Bivio::Biz::Model::Lock
        Bivio::Biz::Action::ReportDate
        Bivio::Biz::Model::MemberSummaryList->execute_load_all
        Bivio::UI::HTML::Club::MemberList
        next=CLUB_ACCOUNTING_MEMBER_LIST
        help=member-summary
        want_query=0
    )],
    # NOTE: This must not be CLUB_ACCOUNTING_REPORT_*, because
    # AccountingReportForm knows the list of accounting reports with
    # a pattern match.
    [qw(
        CLUB_ACCOUNTING_REPORT
        13
        CLUB
        ACCOUNTING_READ
        ?/accounting/reports
        Bivio::Biz::Model::AccountingReportForm
        Bivio::UI::HTML::Club::AccountingReport
        next=CLUB_INTRO
        help=accounting-reports
    )],
    [qw(
        CLUB_ADMIN_USER_LIST
        14
        CLUB
        ADMIN_READ&MEMBER_READ
        ?/admin/roster
        Bivio::Biz::Model::ClubUserList->execute_load_all_with_query
        Bivio::UI::HTML::Club::UserList
        next=CLUB_ADMIN_USER_LIST
        help=club-roster
    )],
    [qw(
        CLUB_REFERRAL
        15
        CLUB
        LOGIN
        ?/ref
        Bivio::Biz::Action::Referral
    )],
    [qw(
        USER_REFERRAL
        16
        USER
        LOGIN
        ?/ref
        Bivio::Biz::Action::Referral
    )],
    [qw(
        CLUB_COMMUNICATIONS_MAIL_LIST
        17
        CLUB
        MAIL_READ
        ?/mail
        Bivio::Biz::Action::PublicRealm
        Bivio::Biz::Model::MailList->execute_load_page
        Bivio::Biz::Model::MailListForm->execute_if_allowed
        Bivio::UI::HTML::Club::MailList
        next=CLUB_COMMUNICATIONS_MAIL_LIST
        help=mail
    )],
    [qw(
        CLUB_COMMUNICATIONS_MAIL_DETAIL
        18
        CLUB
        MAIL_READ
        ?/mail-msg
        Bivio::Biz::Action::PublicRealm
        Bivio::Biz::Model::MailList->execute_load_this
        Bivio::Biz::Model::MailPartList->execute_load_all
        Bivio::UI::HTML::Club::MailDetail
        help=mail
    )],
    # The string msg-part/*?t=NNN is encoded in the MAIL_CACHE generation
    # code. Path info (/*) is ignored by MailPartDownload, because it isn't
    # a unique identifier.  It is there so attachments can be saved
    # to disk nicely.
    [qw(
        CLUB_COMMUNICATIONS_MAIL_PART
        19
        CLUB
        MAIL_READ
        ?/msg-part/*
        Bivio::Biz::Action::PublicRealm
        Bivio::Biz::Action::MailPartDownload
    )],
    [qw(
        CLUB_COMMUNICATIONS_MAIL_PART_SAVE
        20
        CLUB
        DOCUMENT_WRITE
        ?/msg-part-save
        Bivio::Biz::Action::PublicRealm
        Bivio::Type::FileVolume->execute_file
        Bivio::Biz::Model::FileDirectoryList->execute_load_all
	Bivio::Biz::Model::MailPartSaveForm
	Bivio::UI::HTML::Club::MailPartSave
        next=CLUB_COMMUNICATIONS_MAIL_DETAIL
        help=mail
    )],
#21-22
    [qw(
	CLUB_ACCOUNTING_REPORT_VALUATION_STATEMENT
	23
        CLUB
        ACCOUNTING_READ&INVESTMENT_READ&ACCOUNT_READ
        ?/accounting/reports/valuation
        Bivio::Biz::Model::Lock
        Bivio::Biz::Action::ReportDate
        Bivio::Biz::Action::LocalDateHack
	Bivio::Biz::Model::AccountValuationList->execute_load_all
	Bivio::Biz::Model::InstrumentValuationList->execute_load_all
	Bivio::UI::HTML::Club::ValuationReport
        help=valuation-report
    )],
    [qw(
        CLUB_ACCOUNTING_REPORT_INVESTMENT_SUMMARY
        24
        CLUB
        ACCOUNTING_READ&INVESTMENT_READ
        ?/accounting/reports/investment
        Bivio::Biz::Model::Lock
        Bivio::Biz::Action::ReportDate
        Bivio::Biz::Action::LocalDateHack
        Bivio::Biz::Model::InstrumentSummaryList->execute_load_all
        Bivio::UI::HTML::Club::InstrumentSummaryReport
        next=CLUB_ACCOUNTING_REPORT_INVESTMENT_SUMMARY
        help=investment-report
    )],
    [qw(
        CLUB_ACCOUNTING_REPORT_MEMBER_SUMMARY
        26
        CLUB
        ACCOUNTING_READ&MEMBER_READ
        ?/accounting/reports/member
        Bivio::Biz::Model::Lock
        Bivio::Biz::Action::ReportDate
        Bivio::Biz::Action::LocalDateHack
        Bivio::Biz::Model::MemberSummaryList->execute_load_all
        Bivio::UI::HTML::Club::MemberSummaryReport
        next=CLUB_ACCOUNTING_REPORT_MEMBER_SUMMARY
    )],
    [qw(
        CLUB_ACCOUNTING_REPORT_CASH_ACCOUNT_SUMMARY
        27
        CLUB
        ACCOUNTING_READ&ACCOUNT_READ
        ?/accounting/reports/account
        Bivio::Biz::Action::ReportDate
        Bivio::Biz::Action::LocalDateHack
        Bivio::Biz::Model::AccountSummaryList->execute_load_all
        Bivio::UI::HTML::Club::AccountSummaryReport
        help=account-report
    )],
    [qw(
        CLUB_ADMIN_EC_SUBSCRIPTIONS
        28
        CLUB
        ADMIN_READ
        ?/admin/subscriptions
        Bivio::Type::ECSubscription->execute_account_sync
        Bivio::Biz::Model::ECSubscriptionPriceList->execute_for_type_and_realm
        Bivio::Biz::Model::ECSubscriptionList->execute_load_all_with_query
        Bivio::Biz::Model::ECSubscriptionListForm->execute_if_allowed
        Bivio::UI::HTML::Club::ECSubscriptionList
        next=CLUB_ADMIN_EC_SUBSCRIPTIONS
        require_secure=1
    )],
    [qw(
        CLUB_ADMIN_EC_SUBSCRIBE_ACCOUNT_SYNC
        29
        CLUB
        ADMIN_READ
        ?/admin/subscribe/account-sync
        Bivio::Biz::Model::Lock
        Bivio::Type::ECSubscription->execute_account_sync
        Bivio::Biz::Model::ECSubscriptionForm
        Bivio::UI::HTML::Club::ECSubscription
        next=CLUB_ADMIN_EC_ACCOUNT_SYNC_DONE
        cancel=CLUB_ADMIN_EC_PAYMENT_CANCELLED
        require_secure=1
    )],
    [qw(
        CLUB_ADMIN_EC_SUBSCRIBE_ACCOUNT_KEEPER
        30
        CLUB
        ADMIN_READ
        ?/admin/subscribe/account-keeper
        Bivio::Biz::Model::Lock
        Bivio::Type::ECSubscription->execute_account_keeper
        Bivio::Biz::Model::ECSubscriptionForm
        Bivio::UI::HTML::Club::ECSubscription
        next=CLUB_ADMIN_EC_ACCOUNT_SYNC_DONE
        cancel=CLUB_ADMIN_EC_PAYMENT_CANCELLED
        require_secure=1
    )],
    [qw(
        CLUB_ADMIN_EC_SUBSCRIPTION_DETAIL
        31
        CLUB
        ADMIN_READ
        ?/admin/subscription/detail
        Bivio::Biz::Model::ECSubscription->execute_load_this
        Bivio::UI::HTML::Club::ECSubscriptionDetail
        require_secure=1
    )],
    [qw(
        CLUB_ADMIN_EC_SUBSCRIPTION_PAYMENT
        32
        CLUB
        ADMIN_READ
        ?/admin/subscription/renew
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::ECSubscriptionForm
        Bivio::UI::HTML::Club::ECSubscription
        next=CLUB_ADMIN_EC_SUBSCRIBE_DONE
        cancel=CLUB_ADMIN_EC_PAYMENT_CANCELLED
        require_secure=1
    )],
    [qw(
        CLUB_ADMIN_EC_PAYMENTS
        33
        CLUB
        ADMIN_READ
        ?/admin/payments
        Bivio::Biz::Model::ECPaymentList->execute_load_page
        Bivio::UI::HTML::Club::ECPaymentList
        next=CLUB_ADMIN_EC_PAYMENTS
        require_secure=1
    )],
    [qw(
        CLUB_ADMIN_EC_PAYMENT_DETAIL
        34
        CLUB
        ADMIN_READ
        ?/admin/payment/detail
        Bivio::Biz::Model::ECPayment->execute_load_this
        Bivio::UI::HTML::Club::ECPaymentDetail
        next=CLUB_ADMIN_EC_PAYMENT_DETAIL
        require_secure=1
    )],
    [qw(
	ADM_EC_PAYMENTS
	35
        GENERAL
        ADMIN_WRITE
        adm/ec-payments
        Bivio::Biz::Model::ECAdmPaymentList->execute_load_page
	Bivio::UI::HTML::Adm::ECPaymentList
        next=HTTP_DOCUMENT
        require_secure=1
    )],
    [qw(
        EC_PAYMENTS_PROCESS_ALL
        36
        GENERAL
        DOCUMENT_READ
        _ec_payments_process_all
        Bivio::Biz::Action::ECPaymentProcessAll
    )],
    # This task runs as the user who entered the credit card info in CLUB
    [qw(
        CLUB_ADMIN_EC_PROCESS_PAYMENT
        37
        CLUB
        ADMIN_READ
        !
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::ECPayment->execute_process
    )],
    [qw(
        CLUB_ADMIN_EC_PAYMENT_CANCELLED
        38
        CLUB
        ADMIN_READ
        ?/admin/subscribe/cancelled
        Bivio::UI::HTML::Club::ECPaymentCancelled
    )],
    [qw(
	GENERAL_PRIVACY
	39
        GENERAL
        DOCUMENT_READ
        hm/safe.html
        Bivio::Biz::Action::HTTPDocument
    )],
#TODO: Probably should be TargetRealm->execute_this_member, but difficult to
#      use right now.
    [qw(
        CLUB_ACCOUNTING_MEMBER_DETAIL
        40
        CLUB
        ACCOUNTING_READ&MEMBER_READ&ACCOUNT_READ
        ?/accounting/member/detail
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::MemberTransactionList->execute_load_page
        Bivio::Biz::Model::RealmUser->execute_load_parent
        Bivio::Biz::Model::AllMemberList->execute_load_all
        Bivio::UI::HTML::Club::MemberDetail
        help=member-detail
    )],
    [qw(
        CLUB_ACCOUNTING_INVESTMENT_DETAIL
        41
        CLUB
        ACCOUNTING_READ&ACCOUNT_READ&INVESTMENT_READ
        ?/accounting/investment/detail
        Bivio::Biz::Model::Lock
        Bivio::Biz::Action::ReportDate
        Bivio::Biz::Model::InstrumentTransactionList->execute_load_page
        Bivio::Biz::Model::RealmInstrument->execute_load_parent
        Bivio::Biz::Model::InstrumentSummaryList->execute_load_all
        Bivio::UI::HTML::Club::InstrumentDetail
        help=investment-detail
    )],
    [qw(
        CLUB_ACCOUNTING_ACCOUNT_DETAIL
        42
        CLUB
        ACCOUNTING_READ&ACCOUNT_READ&INVESTMENT_READ&MEMBER_READ
        ?/accounting/account/detail
        Bivio::Biz::Model::Lock
        Bivio::Biz::Action::ReportDate
        Bivio::Biz::Model::AccountTransactionList->execute_load_page
        Bivio::Biz::Model::RealmAccount->execute_load_parent
        Bivio::Biz::Model::UnassignedTypeForm
        Bivio::Biz::Model::AccountSummaryList->execute_load_all
        Bivio::UI::HTML::Club::AccountDetail
        next=CLUB_ACCOUNTING_ACCOUNT_DETAIL
        help=account-detail
    )],
    [qw(
        CLUB_ACCOUNTING_MEMBER_PAYMENT
        43
        CLUB
        ACCOUNTING_WRITE&MEMBER_WRITE
        ?/accounting/member/payment
        Bivio::Biz::Model::Lock
        Bivio::Type::EntryType->execute_member_payment
        Bivio::Biz::Model::MemberList->execute_load_all_active
        Bivio::Biz::Model::RealmAccountList->execute_load_all
        Bivio::Biz::Model::SingleDepositForm
        Bivio::UI::HTML::Club::MemberPayment
        next=CLUB_ACCOUNTING_MEMBER_LIST
        help=member-transactions
    )],
    # This needs to be a redirect, because we need the "directory" to
    # be correct so MESSAGE_PART works.
    [qw(
        DEPRECATED_CLUB_COMMUNICATIONS_MAIL_DETAIL
        44
        CLUB
        MAIL_READ
        ?/mail/msg
        Bivio::Biz::Action::ClientRedirect->execute_next
        next=CLUB_COMMUNICATIONS_MAIL_DETAIL
    )],
    [qw(
        CLUB_ACCOUNTING_ACCOUNT_INTEREST
        45
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/account/interest
        Bivio::Biz::Model::RealmAccountList->execute_load_all
        Bivio::Type::EntryType->execute_cash_interest
        Bivio::Biz::Model::AccountTransactionForm
        Bivio::UI::HTML::Club::AccountInterest
        next=CLUB_ACCOUNTING_ACCOUNT_LIST
        help=account-transactions
    )],
    [qw(
        CLUB_ACCOUNTING_ACCOUNT_DIVIDEND
        46
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/account/dividend
        Bivio::Biz::Model::RealmAccountList->execute_load_all
        Bivio::Type::EntryType->execute_cash_dividend
        Bivio::Biz::Model::AccountTransactionForm
        Bivio::UI::HTML::Club::AccountDividend
        next=CLUB_ACCOUNTING_ACCOUNT_LIST
        help=account-transactions
    )],
    [qw(
        CLUB_ACCOUNTING_ACCOUNT_INCOME
        47
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/account/income
        Bivio::Biz::Model::RealmAccountList->execute_load_all
        Bivio::Type::EntryType->execute_cash_income
        Bivio::Biz::Model::AccountTransactionForm
        Bivio::UI::HTML::Club::AccountIncome
        next=CLUB_ACCOUNTING_ACCOUNT_LIST
        help=account-transactions
    )],
    [qw(
        CLUB_ACCOUNTING_ACCOUNT_EXPENSE
        48
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/account/expense
        Bivio::Biz::Model::RealmAccountList->execute_load_all
        Bivio::Type::EntryType->execute_cash_expense
        Bivio::Biz::Model::AccountTransactionForm
        Bivio::Biz::Model::ExpenseCategoryList->execute_load_all
        Bivio::UI::HTML::Club::AccountExpense
        next=CLUB_ACCOUNTING_ACCOUNT_LIST
        help=account-transactions
    )],
#49
    [qw(
        CLUB_ACCOUNTING_INVESTMENT_SELL
        50
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/investment/sell
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::RealmAccountList->execute_load_valuation_only
        Bivio::Biz::Model::InstrumentSaleForm
        Bivio::UI::HTML::Club::InstrumentSale
        next=CLUB_ACCOUNTING_INVESTMENT_LIST
        help=investment-transactions
    )],
    [qw(
        JAPAN_SURVEY
        52
        GENERAL
        DOCUMENT_READ
        pub/japan_survey
        Bivio::Biz::Model::JapanSurveyForm
        Bivio::Biz::Action::ClientRedirect->JAPAN_SURVEY_TEXT
        next=JAPAN_SURVEY_THANKS
        cancel=HTTP_DOCUMENT
    )],
    [qw(
        JAPAN_SURVEY_THANKS
        53
        GENERAL
        DOCUMENT_READ
        hm/thanks_japan.html
	Bivio::Biz::Action::HTTPDocument
    )],
    [qw(
        CLUB_ADMIN_SELF_ADDRESS_EDIT
        54
        CLUB
        ANY_REALM_USER
        ?/admin/edit/self/address
        Bivio::Biz::Action::TargetRealm->execute_auth_user
        Bivio::Biz::Model::AddressForm
        Bivio::UI::HTML::Realm::EditAddress
        next=CLUB_ADMIN_USER_DETAIL
    )],
    [qw(
        CLUB_ADMIN_SELF_NAME_EDIT
        55
        CLUB
        ANY_REALM_USER
        ?/admin/edit/self/name
        Bivio::Type::NameEdit->execute_both
        Bivio::Biz::Action::TargetRealm->execute_auth_user
        Bivio::Biz::Model::UserNameForm
        Bivio::UI::HTML::User::EditName
        next=CLUB_ADMIN_USER_DETAIL
    )],
    [qw(
        CLUB_ADMIN_SELF_PHONE_EDIT
        56
        CLUB
        ANY_REALM_USER
        ?/admin/edit/self/phone
        Bivio::Biz::Action::TargetRealm->execute_auth_user
        Bivio::Biz::Model::PhoneForm
        Bivio::UI::HTML::Realm::EditPhone
        next=CLUB_ADMIN_USER_DETAIL
    )],
    [qw(
        CLUB_ADMIN_SELF_PASSWORD_EDIT
        57
        CLUB
        ANY_REALM_USER&LOGIN
        ?/admin/edit/self/password
        Bivio::Biz::Action::TargetRealm->execute_auth_user
        Bivio::Biz::Model::PasswordForm
        Bivio::UI::HTML::User::EditPassword
        next=CLUB_ADMIN_USER_DETAIL
    )],
    [qw(
	DEMO_REDIRECT
	58
        GENERAL
        DOCUMENT_READ
        demo
	Bivio::Biz::Action::DemoClubRedirect->execute_if_anonymous
        Bivio::Biz::Action::ClientRedirect->execute_next
        next=USER_DEMO_CLUB_REDIRECT
    )],
    [qw(
	USER_DEMO_CLUB_REDIRECT
	59
        USER
        DOCUMENT_READ
        ?/demo
        Bivio::Biz::Model::Lock
	Bivio::Biz::Action::DemoClubRedirect->execute_user
        next=CLUB_INTRO
    )],
    [qw(
        CLUB_ACCOUNTING_MEMBER_FEE
        60
        CLUB
        ACCOUNTING_WRITE&MEMBER_WRITE
        ?/accounting/member/fee
        Bivio::Biz::Model::Lock
        Bivio::Type::EntryType->execute_member_payment_fee
        Bivio::Biz::Model::MemberList->execute_load_all_active
        Bivio::Biz::Model::RealmAccountList->execute_load_valuation_only
	Bivio::Biz::Model::SingleDepositForm
        Bivio::UI::HTML::Club::MemberFee
        next=CLUB_ACCOUNTING_MEMBER_LIST
        help=member-transactions
    )],
    [qw(
        MAIL_SUPPORT
        61
        GENERAL
        DOCUMENT_READ
        pub/mail-support
        Bivio::Biz::Model::MailSupportForm
        Bivio::UI::HTML::General::MailSupport
        next=HTTP_DOCUMENT
    )],
    [qw(
        JAPAN_SURVEY_TEXT
        62
        GENERAL
        DOCUMENT_READ
        hm/intro_japan.html
	Bivio::Biz::Action::HTTPDocument
    )],
    # This URI must identify the user agreement document file.
    [qw(
        USER_AGREEMENT_TEXT
        63
        GENERAL
        DOCUMENT_READ
        hm/user.html
        Bivio::Biz::Action::HTTPDocument
    )],
    [qw(
        USER_CREATE
        64
        GENERAL
        LOGIN
        pub/register:pub/create_user
        Bivio::Biz::Model::RealmInvite->check_accept
        Bivio::Biz::Model::CreateUserForm
        Bivio::UI::HTML::General::CreateUser
        next=USER_NEW
        cancel=HTTP_DOCUMENT
    )],
    # Default page for users, see MY_BIVIO_REDIRECT
    [qw(
        USER_HOME
        65
        USER
        DOCUMENT_READ
        ?
        Bivio::UI::HTML::User::Home
    )],
    [qw(
        USER_ADMIN_INFO
        66
        USER
        ADMIN_READ
        ?/admin:?/admin/info
        Bivio::Biz::Model::User->execute_load
        Bivio::UI::HTML::User::AdminInfo
    )],
    [qw(
        USER_CLUB_LIST
        67
        USER
        ADMIN_READ
        ?/clubs
        Bivio::Biz::Model::UserClubList->execute_load_all
        Bivio::UI::HTML::User::ClubList
    )],
    [qw(
        USER_ADMIN_NAME_EDIT
        68
        USER
        ADMIN_WRITE
        ?/admin/edit/name
        Bivio::Type::NameEdit->execute_both
        Bivio::Biz::Action::TargetRealm->execute_auth_realm
        Bivio::Biz::Model::UserNameForm
        Bivio::UI::HTML::User::EditName
        next=USER_ADMIN_INFO
    )],
    [qw(
        CLUB_CREATE
        69
        USER
        ADMIN_WRITE
        ?/create-club:?/create_club
        Bivio::Biz::Model::CreateClubForm
        Bivio::UI::HTML::User::CreateClub
        next=CLUB_CREATED
        cancel=USER_CLUB_LIST
    )],
    [qw(
        CLUB_HOME
        70
        CLUB
        DOCUMENT_READ
        ?
        Bivio::Type::FileVolume->execute_file
        Bivio::Biz::Action::PublicRealm
        Bivio::Biz::Model::FileHomePageList->execute_load_all
        Bivio::Biz::Action::HomePageRedirect
        Bivio::UI::HTML::Club::Home
        help=club-home
    )],
    [qw(
        USER_ADMIN_PASSWORD_EDIT
        71
        USER
        ADMIN_WRITE&LOGIN
        ?/admin/edit/password
        Bivio::Biz::Action::TargetRealm->execute_auth_realm
        Bivio::Biz::Model::PasswordForm
        Bivio::UI::HTML::User::EditPassword
        next=USER_ADMIN_INFO
    )],
    [qw(
        USER_ADMIN_ADDRESS_EDIT
        72
        USER
        ADMIN_WRITE
        ?/admin/edit/address
        Bivio::Biz::Action::TargetRealm->execute_auth_realm
        Bivio::Biz::Model::AddressForm
        Bivio::UI::HTML::Realm::EditAddress
        next=USER_ADMIN_INFO
    )],
    [qw(
        USER_ADMIN_PHONE_EDIT
        73
        USER
        ADMIN_WRITE
        ?/admin/edit/phone
        Bivio::Biz::Action::TargetRealm->execute_auth_realm
        Bivio::Biz::Model::PhoneForm
        Bivio::UI::HTML::Realm::EditPhone
        next=USER_ADMIN_INFO
    )],
    [qw(
        USER_ADMIN_EC_PAYMENT
        75
        USER
        ADMIN_READ
        ?/admin/pay/merchandise
        Bivio::Biz::Model::Lock
        Bivio::Type::ECSubscription->execute_unknown
        Bivio::Type::ECPayment->execute_merchandise
        Bivio::Biz::Model::ECSubscriptionForm
        Bivio::UI::HTML::Club::ECSubscription
        next=USER_ADMIN_INFO
        require_secure=1
    )],
    [qw(
        CLUB_ADMIN_INVITE_LIST
        76
        CLUB
        ADMIN_READ&MEMBER_READ
        ?/admin/invites:?/admin/invitations
        Bivio::Biz::Model::RealmInviteList->execute_load_all_with_query
        Bivio::Biz::Model::ClubUserList->execute_load_all_active
        Bivio::UI::HTML::Club::InviteList
        help=adding-members-guests
    )],
    # This technically doesn't have to be in your domain
    [qw(
        REALM_INVITE_ACCEPT
        77
        GENERAL
        DOCUMENT_READ
        pub/join
        Bivio::Biz::Model::RealmInvite->execute_accept
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::RealmInviteAcceptForm
        Bivio::UI::HTML::General::InviteAccept
        cancel=MY_CLUB_SITE
        next=CLUB_USER_NEW
        NOT_FOUND=REALM_INVITE_NOT_FOUND
    )],
# Another task here which handles does the invite accept part.
# May need multiple tasks, because the cancels will be different
    # We use RealmUserList and ClubUserList, because this is a detail
    # and we need the whole list for the chooser and the individual
    # validated by the normal "this" loading.
    [qw(
        CLUB_ADMIN_USER_DETAIL
        78
        CLUB
        ADMIN_READ&MEMBER_READ
        ?/admin/roster/detail
        Bivio::Biz::Model::ClubUserList->execute_load_this_or_first
        Bivio::Biz::Action::TargetRealm->execute_this
        Bivio::Biz::Model::RealmUserList->execute_load_all
        Bivio::UI::HTML::Club::UserDetail
        NOT_FOUND=CLUB_ADMIN_USER_LIST
    )],
    [qw(
        CLUB_ADMIN_MEMBER_TITLE_EDIT
        79
        CLUB
        ADMIN_WRITE&MEMBER_WRITE
        ?/admin/edit/member/privileges
        Bivio::Biz::Model::ClubUserList->execute_load_this
        Bivio::Biz::Action::TargetRealm->execute_this_member
        Bivio::Biz::Model::ClubMemberTitleForm
        Bivio::UI::HTML::Club::EditMemberTitle
        next=CLUB_ADMIN_USER_DETAIL
        help=changing-privileges
    )],
    [qw(
        CLUB_ACCOUNTING_INVESTMENT_LOOKUP
        80
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/investment/lookup
        Bivio::Biz::Model::InstrumentLookupForm
        Bivio::UI::HTML::Club::InstrumentLookup
        next=CLUB_ACCOUNTING_INVESTMENT_LIST
        help=investment-transactions
    )],
    [qw(
        CLUB_ACCOUNTING_INVESTMENT_BUY
        81
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/investment/buy
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::RealmAccountList->execute_load_valuation_only
        Bivio::Biz::Model::InstrumentBuyForm
        Bivio::UI::HTML::Club::InstrumentBuy
        next=CLUB_ACCOUNTING_INVESTMENT_LIST
        help=investment-transactions
    )],
    [qw(
	ADM_SUBSTITUTE_USER
	82
        GENERAL
        ADMIN_WRITE
        adm/su
	Bivio::Biz::Model::SubstituteUserForm
	Bivio::UI::HTML::Adm::SubstituteUser
        next=MY_CLUB_SITE
        cancel=HTTP_DOCUMENT
        require_secure=1
    )],
    [qw(
	GENERAL_CONTACT
	83
        GENERAL
        DOCUMENT_READ
        hm/contact.html
        Bivio::Biz::Action::HTTPDocument
    )],
    # Redirect to MY_SITE by default, because the user may not be
    # logged in and USER_HOME requires an auth_realm.
#TODO: Make this goto/*  I can't do that now, because too close to release
#      Need to modify ClientRedirect to throw away path info in default case.
    [qw(
	CLIENT_REDIRECT
	84
        GENERAL
        DOCUMENT_READ
        goto
        Bivio::Biz::Action::ClientRedirect->execute_query
        next=MY_SITE
    )],
    [qw(
        CLUB_ADMIN_EC_SUBSCRIBE_DONE
        85
        CLUB
        ADMIN_READ
        ?/admin/subscribe/done
        Bivio::UI::HTML::Club::ECSubscriptionDone
    )],
#TODO: Cancel is broken on detail, because FormModel doesn't do the right thing
    [qw(
        CLUB_ACCOUNTING_INVESTMENT_TRANSACTION_DELETE
        86
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/investment/delete
        Bivio::Biz::Model::TransactionDeleteForm
        Bivio::UI::HTML::Club::TransactionDelete
        next=CLUB_ACCOUNTING_INVESTMENT_LIST
        help=deleting-transactions
    )],
#TODO: Cancel is broken on detail, because FormModel doesn't do the right thing
    [qw(
        CLUB_ACCOUNTING_MEMBER_TRANSACTION_DELETE
        87
        CLUB
        ACCOUNTING_WRITE&MEMBER_WRITE
        ?/accounting/member/delete
        Bivio::Biz::Model::TransactionDeleteForm
        Bivio::UI::HTML::Club::TransactionDelete
        next=CLUB_ACCOUNTING_MEMBER_LIST
        help=deleting-transactions
    )],
    [qw(
        CLUB_ACCOUNTING_ACCOUNT_TRANSACTION_DELETE
        88
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/account/delete
        Bivio::Biz::Model::TransactionDeleteForm
        Bivio::UI::HTML::Club::TransactionDelete
        next=CLUB_ACCOUNTING_ACCOUNT_LIST
        help=deleting-transactions
    )],
    [qw(
        CLUB_ACCOUNTING_INVESTMENT_INCOME
        89
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/investment/income
        Bivio::Biz::Model::RealmAccountList->execute_load_valuation_only
        Bivio::Biz::Model::InstrumentIncomeForm
        Bivio::UI::HTML::Club::InstrumentIncome
        next=CLUB_ACCOUNTING_INVESTMENT_LIST
        help=investment-transactions
    )],
    [qw(
        CLUB_ACCOUNTING_INVESTMENT_SPLIT
        90
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/investment/split
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::RealmAccountList->execute_load_valuation_only
        Bivio::Biz::Model::InstrumentSplitForm
        Bivio::UI::HTML::Club::InstrumentSplit
        next=CLUB_ACCOUNTING_INVESTMENT_LIST
        help=investment-transactions
    )],
    [qw(
        REALM_INVITE_NOT_FOUND
        91
        GENERAL
        DOCUMENT_READ
        !
        Bivio::UI::HTML::ErrorPages->execute_invite_not_found
    )],
    [qw(
        CLUB_SETUP_SWITCHOVER_CHOICE
        92
        CLUB
        ADMIN_READ
        ?/switchover-choice
        Bivio::Biz::Model::RealmUser->execute_auth_user
        Bivio::UI::HTML::Club::New
        help=switchover-date
    )],
    [qw(
        USER_NEW
        93
        USER
        DOCUMENT_READ
        ?/new
        Bivio::Biz::Model::Email->execute_load
        Bivio::UI::HTML::User::New
    )],
    [qw(
        CLUB_USER_NEW
        94
        CLUB
        ANY_REALM_USER
        ?/new-user:?/new_user
        Bivio::Biz::Model::RealmUser->execute_auth_user
        Bivio::Biz::Model::Email->execute_auth_user
        Bivio::UI::HTML::Club::UserNew
    )],
    [qw(
        CLUB_CREATED
        95
        CLUB
        ADMIN_READ
        ?/new
        Bivio::Biz::Model::RealmUser->execute_auth_user
        Bivio::UI::HTML::Club::New
    )],
    [qw(
        CONNECT_USER_CREATE
        96
        GENERAL
        LOGIN
        pub/connect
        Bivio::Biz::Action::ConnectCheckUser
        Bivio::Biz::Model::CreateUserForm
        Bivio::UI::HTML::General::CreateUser
        next=CONNECT_USER_NEW
        cancel=HTTP_DOCUMENT
    )],
    [qw(
        CLUB_ADMIN_PREFERENCES_EDIT
        97
        CLUB
        ADMIN_WRITE
        ?/admin/edit/configuration
        Bivio::Biz::Action::PublicRealm
        Bivio::Biz::Model::ClubPreferencesForm
        Bivio::UI::HTML::Club::EditPreferences
        next=CLUB_ADMIN_TOOLS
        require_context=0
        help=club-configuration
    )],
#TODO: Put user_new state into cookie
    [qw(
        CONNECT_USER_NEW
        98
        USER
        DOCUMENT_READ
        ?/new-connect:?/new_connect
        Bivio::Biz::Model::Email->execute_load
        Bivio::UI::HTML::User::New
    )],
    [qw(
        USER_ADMIN_PROFILE_EDIT
        99
        USER
        ADMIN_WRITE
        ?/admin/edit/profile
        Bivio::Biz::Model::ConnectSurveyForm
        Bivio::UI::HTML::User::EditProfile
        next=USER_ADMIN_PROFILE_EDIT_DONE
        cancel=USER_ADMIN_INFO
    )],
    [qw(
        CONNECT_LOGIN
        100
        GENERAL
        ANY_USER
        pub/connect/login
        Bivio::Biz::Action::ClientRedirect->execute_next
        next=USER_ADMIN_PROFILE_EDIT
    )],
    [qw(
        CLUB_ADMIN_NAME_EDIT
        102
        CLUB
        ADMIN_WRITE
        ?/admin/edit/name
        Bivio::Biz::Action::NotDemoClub
        Bivio::Biz::Action::TargetRealm->execute_auth_realm
        Bivio::Biz::Model::ClubNameForm
        Bivio::UI::HTML::Club::EditName
        next=CLUB_ADMIN_INFO
    )],
    [qw(
        DEMO_CLUB_ACTION_FORBIDDEN
        103
        CLUB
        DOCUMENT_READ
        !
        Bivio::UI::HTML::ErrorPages->execute_demo_club_action_forbidden
    )],
    [qw(
	USER_REFERRAL_CLIENT_REDIRECT
	104
        USER
        LOGIN
        ?/goto/*
        Bivio::Biz::Action::ClientRedirect->execute_query
        next=HTTP_DOCUMENT
    )],
    [qw(
	CLUB_REFERRAL_CLIENT_REDIRECT
	105
        CLUB
        LOGIN
        ?/goto/*
        Bivio::Biz::Action::ClientRedirect->execute_query
        next=HTTP_DOCUMENT
    )],
    [qw(
        CLUB_ADMIN_MEMBER_EMAIL_EDIT
        106
        CLUB
        ADMIN_WRITE&MEMBER_WRITE
        ?/admin/edit/member/email
        Bivio::Biz::Model::ClubUserList->execute_load_this
        Bivio::Biz::Action::TargetRealm->execute_this_real_member
        Bivio::Biz::Model::EmailForm
        Bivio::UI::HTML::Realm::EditEmail
        next=CLUB_ADMIN_USER_DETAIL
    )],
    [qw(
        DEFAULT_ERROR_REDIRECT_FORBIDDEN
        107
        GENERAL
        DOCUMENT_READ
        !
        Bivio::UI::HTML::ErrorPages->execute_forbidden
    )],
    [qw(
        USER_ADMIN_PROFILE_EDIT_DONE
        108
        USER
        ADMIN_WRITE
        ?/admin/edit/profile/done
        Bivio::UI::HTML::User::EditProfileDone
    )],
    [qw(
        CLUB_COMMUNICATIONS_FILE_READ
        109
        CLUB
        DOCUMENT_READ
        ?/files/*
        Bivio::Biz::Model::Lock
        Bivio::Biz::Action::PublicRealm
        Bivio::Type::FileVolume->execute_file
        Bivio::Biz::Model::FilePathList
        Bivio::Biz::Action::FileDownload->execute_if_file
        Bivio::Biz::Model::FileTreeList->execute_load_all_with_query
        Bivio::Biz::Model::FileTreeListForm->execute_if_allowed
        Bivio::UI::HTML::Club::FileTree
	next=CLUB_COMMUNICATIONS_FILE_READ
        NOT_FOUND=FILE_READ_NOT_FOUND
        help=files
    )],
    [qw(
        CLUB_COMMUNICATIONS_FILE_DELETE
        110
        CLUB
        DOCUMENT_WRITE
        ?/file-delete/*
        Bivio::Biz::Model::Lock
        Bivio::Biz::Action::PublicRealm
        Bivio::Type::FileVolume->execute_file
        Bivio::Biz::Model::FileDirectoryList->execute_load_all
        Bivio::Biz::Model::FilePathList
        Bivio::Biz::Model::FileDeleteForm
        Bivio::UI::HTML::Club::FileDelete
	next=CLUB_COMMUNICATIONS_FILE_READ
        help=files
    )],
    [qw(
        CLUB_COMMUNICATIONS_FILE_UPLOAD
        111
        CLUB
        DOCUMENT_WRITE
        ?/file-upload/*:?/file_upload/*
        Bivio::Biz::Model::Lock
        Bivio::Biz::Action::PublicRealm
        Bivio::Type::FileVolume->execute_file
        Bivio::Biz::Model::FilePathList
        Bivio::Biz::Model::FileUploadForm
        Bivio::UI::HTML::Widget::FilePageHeading
        Bivio::UI::HTML::Club::FileUpload
	next=CLUB_COMMUNICATIONS_FILE_READ
        help=files
    )],
    [qw(
        CLUB_COMMUNICATIONS_FILE_REPLACE
        112
        CLUB
        DOCUMENT_WRITE
        ?/file-replace/*:?/file_replace/*
        Bivio::Biz::Model::Lock
        Bivio::Biz::Action::PublicRealm
        Bivio::Type::FileVolume->execute_file
        Bivio::Biz::Model::FilePathList
        Bivio::Biz::Model::FileUploadForm
        Bivio::UI::HTML::Widget::FilePageHeading->execute_no_links
        Bivio::UI::HTML::Club::FileReplace
	next=CLUB_COMMUNICATIONS_FILE_READ
        help=files
    )],
    [qw(
        CLUB_COMMUNICATIONS_FILE_CREATE_DIRECTORY
        113
        CLUB
        DOCUMENT_WRITE
        ?/new-file-folder/*:?/new_file_folder/*
        Bivio::Biz::Model::Lock
        Bivio::Biz::Action::PublicRealm
        Bivio::Type::FileVolume->execute_file
        Bivio::Biz::Model::FilePathList
        Bivio::Biz::Model::CreateDirectoryForm
        Bivio::UI::HTML::Widget::FilePageHeading
        Bivio::UI::HTML::Club::CreateDirectory
	next=CLUB_COMMUNICATIONS_FILE_READ
    )],
    [qw(
        CLUB_COMMUNICATIONS_FILE_SEARCH
        114
        CLUB
        DOCUMENT_READ
        ?/file-search/*
        Bivio::Biz::Action::PublicRealm
        Bivio::Type::FileVolume->execute_file
        Bivio::Biz::Model::FileDirectoryList->execute_load_all
        Bivio::Biz::Action::FileSearchRedirect
    )],
    [qw(
        FILE_READ_NOT_FOUND
        115
        GENERAL
        DOCUMENT_READ
        !
        Bivio::UI::HTML::ErrorPages->execute_file_read_not_found
    )],
#116
    [qw(
        CLUB_LEGACY_UPLOAD_INSECURE_ACK
        117
        CLUB
        ACCOUNTING_WRITE&MEMBER_WRITE&ADMIN_WRITE
        ?/accounting/insecure-import-ack
        Bivio::Biz::Action::NotDemoClub
        Bivio::UI::HTML::Club::LegacyClubUploadInsecureAck
        next=CLUB_LEGACY_UPLOAD_INSECURE
        cancel=CLUB_ADMIN_TOOLS
        help=importing-naic-club-accounting
    )],
    [qw(
        CLUB_ACCOUNTING_ACCOUNT_TRANSFER
        118
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/account/transfer
        Bivio::Biz::Model::RealmAccountList->execute_load_valuation_only
        Bivio::Biz::Model::AccountTransferForm
        Bivio::UI::HTML::Club::AccountTransfer
        next=CLUB_ACCOUNTING_ACCOUNT_LIST
        help=account-transactions
    )],
    [qw(
        DEFAULT_ERROR_REDIRECT_NO_RESOURCES
        119
        GENERAL
        DOCUMENT_READ
        !
        Bivio::UI::HTML::ErrorPages->execute_no_resources
    )],
    [qw(
        CLUB_ADMIN_ADDRESS_EDIT
        120
        CLUB
        ADMIN_WRITE
        ?/admin/edit/address
        Bivio::Biz::Action::TargetRealm->execute_auth_realm
        Bivio::Biz::Model::AddressForm
        Bivio::UI::HTML::Realm::EditAddress
        next=CLUB_ADMIN_INFO
    )],
    [qw(
        CLUB_ADMIN_MEMBER_ADDRESS_EDIT
        121
        CLUB
        ADMIN_WRITE&MEMBER_WRITE
        ?/admin/edit/member/address
        Bivio::Biz::Model::ClubUserList->execute_load_this
        Bivio::Biz::Action::TargetRealm->execute_this_member_or_withdrawn
        Bivio::Biz::Model::AddressForm
        Bivio::UI::HTML::Realm::EditAddress
        next=CLUB_ADMIN_USER_DETAIL
    )],
    [qw(
        CLUB_ADMIN_SELF_TAX_ID_EDIT
        122
        CLUB
        ANY_REALM_USER&LOGIN
        ?/admin/edit/self/tax-id:?/admin/edit/self/tax_id
        Bivio::Biz::Action::TargetRealm->execute_auth_user
        Bivio::Biz::Model::TaxIdForm
        Bivio::UI::HTML::Realm::EditTaxId
        next=CLUB_ADMIN_USER_DETAIL
        require_secure=1
    )],
    [qw(
        CLUB_ADMIN_MEMBER_TAX_ID_EDIT
        123
        CLUB
        ADMIN_WRITE&MEMBER_WRITE&LOGIN
        ?/admin/edit/member/tax-id:?/admin/edit/member/tax_id
        Bivio::Biz::Model::ClubUserList->execute_load_this
        Bivio::Biz::Action::TargetRealm->execute_this_member_or_withdrawn
        Bivio::Biz::Model::TaxIdForm
        Bivio::UI::HTML::Realm::EditTaxId
        next=CLUB_ADMIN_USER_DETAIL
        require_secure=1
    )],
    [qw(
        USER_ADMIN_TAX_ID_EDIT
        124
        USER
        ADMIN_WRITE&LOGIN
        ?/admin/edit/tax-id:?/admin/edit/member/tax-id:?/admin/edit/member/tax_id
        Bivio::Biz::Action::TargetRealm->execute_auth_realm
        Bivio::Biz::Model::TaxIdForm
        Bivio::UI::HTML::Realm::EditTaxId
        next=USER_ADMIN_INFO
        require_secure=1
    )],
    [qw(
        CLUB_ADMIN_TAX_ID_EDIT
        125
        CLUB
        ADMIN_WRITE&LOGIN
        ?/admin/edit/tax-id:?/admin/edit/tax_id
        Bivio::Biz::Action::TargetRealm->execute_auth_realm
        Bivio::Biz::Model::TaxIdForm
        Bivio::UI::HTML::Realm::EditTaxId
        next=CLUB_ADMIN_INFO
        require_secure=1
        help=tax-id
    )],
    [qw(
        CLUB_ADMIN_INFO
        126
        CLUB
        ADMIN_READ
        ?/admin/info
        Bivio::UI::HTML::Club::AdminInfo
        help=club-info
    )],
    [qw(
        USER_ADMIN_EMAIL_EDIT
        127
        USER
        ADMIN_WRITE
        ?/admin/edit/email
        Bivio::Biz::Action::TargetRealm->execute_auth_realm
        Bivio::Biz::Model::EmailForm
        Bivio::UI::HTML::Realm::EditEmail
        next=USER_ADMIN_INFO
    )],
    [qw(
        CLUB_ADMIN_SELF_EMAIL_EDIT
        128
        CLUB
        ANY_REALM_USER
        ?/admin/edit/self/email
        Bivio::Biz::Action::TargetRealm->execute_auth_user
        Bivio::Biz::Model::EmailForm
        Bivio::UI::HTML::Realm::EditEmail
        next=CLUB_ADMIN_USER_DETAIL
    )],
    [qw(
        CLUB_ADMIN_PHONE_EDIT
        129
        CLUB
        ADMIN_WRITE
        ?/admin/edit/phone
        Bivio::Biz::Action::TargetRealm->execute_auth_realm
        Bivio::Biz::Model::PhoneForm
        Bivio::UI::HTML::Realm::EditPhone
        next=CLUB_ADMIN_INFO
    )],
    # Order of lists is important.  RealmAccountList must be last
    [qw(
        CLUB_ACCOUNTING_PAYMENT
        130
        CLUB
        ACCOUNTING_WRITE&MEMBER_WRITE
        ?/accounting/payment
        Bivio::Biz::Model::Lock
        Bivio::Type::EntryType->execute_member_payment
        Bivio::Biz::Model::MemberList->execute_load_all_active
        Bivio::Biz::Model::RealmAccountList->execute_load_all
        Bivio::Biz::Model::MultipleDepositForm
        Bivio::UI::HTML::Club::MultiplePayment
        next=CLUB_ACCOUNTING_MEMBER_LIST
        help=member-transactions
    )],
    # Order of lists is important.  RealmAccountList must be last
    [qw(
        CLUB_ACCOUNTING_FEE
        131
        CLUB
        ACCOUNTING_WRITE&MEMBER_WRITE
        ?/accounting/fee
        Bivio::Biz::Model::Lock
        Bivio::Type::EntryType->execute_member_payment_fee
        Bivio::Biz::Model::MemberList->execute_load_all
        Bivio::Biz::Model::RealmAccountList->execute_load_valuation_only
        Bivio::Biz::Model::MultipleDepositForm
        Bivio::UI::HTML::Club::MultipleFee
        next=CLUB_ACCOUNTING_MEMBER_LIST
        help=member-transactions
    )],
    [qw(
        CLUB_LEGACY_UPLOAD
        132
        CLUB
        ACCOUNTING_WRITE&MEMBER_WRITE&ADMIN_WRITE
        ?/accounting/import
        Bivio::Biz::Action::NotDemoClub
        Bivio::Biz::Action::ImportMacRedirect
        Bivio::Biz::Model::Club->execute_load
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::LegacyClubUploadForm
        Bivio::UI::HTML::Club::LegacyClubUpload
        next=CLUB_LEGACY_SECURITY_RECONCILIATION
        cancel=CLUB_ADMIN_TOOLS
        require_secure=1
        help=importing-naic-club-accounting
    )],
    [qw(
        CLUB_LEGACY_UPLOAD_INSECURE
        133
        CLUB
        ACCOUNTING_WRITE&MEMBER_WRITE&ADMIN_WRITE
        ?/accounting/insecure-import
        Bivio::Biz::Action::NotDemoClub
        Bivio::Biz::Model::Club->execute_load
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::LegacyClubUploadForm
        Bivio::UI::HTML::Club::LegacyClubUpload
        next=CLUB_LEGACY_SECURITY_RECONCILIATION
        cancel=CLUB_ADMIN_TOOLS
        help=importing-naic-club-accounting
    )],
    [qw(
        CLUB_ADMIN_SHADOW_MEMBER_INVITE
        134
        CLUB
        ACCOUNTING_WRITE&MEMBER_WRITE&ADMIN_WRITE
        ?/admin/invite/offline_members:?/admin/invite/offline-members
        Bivio::Biz::Action::NotDemoClub
        Bivio::Biz::Model::UninvitedMemberList->execute_load_all_active
        Bivio::Biz::Model::InviteMemberListForm
        Bivio::UI::HTML::Club::InviteMemberList
        next=CLUB_ADMIN_USER_LIST
        help=adding-members-guests
    )],
    [qw(
        CLUB_LEGACY_SECURITY_RECONCILIATION
        135
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/identify/listed-investments:?/accounting/identify/listed_investments
        Bivio::Biz::Action::NotDemoClub
        Bivio::Biz::Model::RealmLocalSecurityList->execute_load_all
        Bivio::Biz::Model::ImportedSecurityReconciliationForm
        Bivio::UI::HTML::Club::ImportedSecurityReconciliation
        next=CLUB_ADMIN_SHADOW_MEMBER_INVITE
        cancel=CLUB_ADMIN_TOOLS
    )],
    [qw(
        CLUB_ACCOUNTING_CLEAR
        136
        CLUB
        ACCOUNTING_WRITE&MEMBER_WRITE&ADMIN_WRITE
        ?/accounting/clear
        Bivio::Biz::Action::NotDemoClub
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::Club->execute_load
        Bivio::Biz::Model::ClearAccountingForm
        Bivio::UI::HTML::Club::ClearAccounting
        next=CLUB_ADMIN_TOOLS
        help=importing-naic-club-accounting
    )],
    [qw(
        CLUB_ADMIN_TOOLS
        137
        CLUB
        ACCOUNTING_WRITE
        ?/admin/tools
        Bivio::Biz::Action::PublicRealm
        Bivio::Biz::Model::RealmLocalSecurityList->execute_load_all
        Bivio::Biz::Model::LocalValuationYearList->execute_load_all
        Bivio::UI::HTML::Club::AdminTools
        help=admin-tools
    )],
    [qw(
        CLUB_LEGACY_UPLOAD_PROCESSOR
        138
        CLUB
        ACCOUNTING_WRITE&MEMBER_WRITE
        !
        Bivio::Biz::Model::Lock
        Bivio::Biz::Action::AccountingImport
    )],
    [qw(
        CLUB_ACCOUNTING_LOCAL_INSTRUMENT
        139
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/unlisted/new
        Bivio::Biz::Model::LocalInstrumentForm
        Bivio::UI::HTML::Club::LocalInstrument
        next=CLUB_ACCOUNTING_INVESTMENT_LIST
        help=unlisted-investments
    )],
    [qw(
        CLUB_ACCOUNTING_LOCAL_VALUATION_DATES
        140
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/valuation/dates
        Bivio::Biz::Model::LocalValuationYearList->execute_load_all
        Bivio::Biz::Model::LocalValuationDateList->execute_load_all
        Bivio::UI::HTML::Club::LocalValuationDates
        help=value-unlisted-investments
    )],
    [qw(
        CLUB_ACCOUNTING_LOCAL_PRICES
        141
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/valuation/prices
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::LocalPriceList->execute_load_all
        Bivio::Biz::Model::LocalPricesForm
        Bivio::UI::HTML::Club::LocalPrices
        next=CLUB_ACCOUNTING_LOCAL_VALUATION_DATES
        help=value-unlisted-investments
    )],
    [qw(
        CLUB_ACCOUNTING_LOCAL_VALUE
        142
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/valuation/new
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::LocalPriceList->execute_load_all
        Bivio::Biz::Model::LocalPricesForm
        Bivio::UI::HTML::Club::LocalPrices
        next=CLUB_ACCOUNTING_INVESTMENT_LIST
        help=value-unlisted-investments
    )],
    [qw(
        DEFAULT_ERROR_REDIRECT_UPDATE_COLLISION
        143
        GENERAL
        DOCUMENT_READ
        !
        Bivio::UI::HTML::ErrorPages->execute_update_collision
    )],
    [qw(
        CLUB_ADMIN_MEMBER_PHONE_EDIT
        145
        CLUB
        ADMIN_WRITE&MEMBER_WRITE
        ?/admin/edit/member/phone
        Bivio::Biz::Model::ClubUserList->execute_load_this
        Bivio::Biz::Action::TargetRealm->execute_this_member_or_withdrawn
        Bivio::Biz::Model::PhoneForm
        Bivio::UI::HTML::Realm::EditPhone
        next=CLUB_ADMIN_USER_DETAIL
    )],
    [qw(
        CLUB_ADMIN_MEMBER_NAME_EDIT
        146
        CLUB
        ADMIN_WRITE&MEMBER_WRITE
        ?/admin/edit/member/name
        Bivio::Type::NameEdit->execute_display_only
        Bivio::Biz::Model::ClubUserList->execute_load_this
        Bivio::Biz::Action::TargetRealm->execute_this_member_or_withdrawn
        Bivio::Biz::Model::UserNameForm
        Bivio::UI::HTML::Club::EditUserName
        next=CLUB_ADMIN_USER_DETAIL
    )],
    [qw(
        CLUB_ADMIN_MEMBER_ADD
        147
        CLUB
        ADMIN_WRITE&MEMBER_WRITE
        ?/admin/add/members
        Bivio::Biz::Action::NotDemoClub
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::NumberedList->execute_load_page
        Bivio::Biz::Model::AddMemberListForm
        Bivio::UI::HTML::Club::AddMemberList
        next=CLUB_ADMIN_USER_LIST
        help=adding-members-guests
    )],
    [qw(
        CLUB_ADMIN_GUEST_INVITE
        148
        CLUB
        ADMIN_WRITE&MEMBER_WRITE
        ?/admin/invite/guests
        Bivio::Biz::Action::NotDemoClub
        Bivio::Biz::Model::NumberedList->execute_load_page
        Bivio::Biz::Model::InviteGuestListForm
        Bivio::UI::HTML::Club::InviteGuestList
        next=CLUB_ADMIN_INVITE_LIST
        cancel=CLUB_ADMIN_USER_LIST
        help=adding-members-guests
    )],
    [qw(
        DEFAULT_ERROR_REDIRECT_CORRUPT_QUERY
        149
        GENERAL
        DOCUMENT_READ
        !
        Bivio::UI::HTML::ErrorPages->execute_corrupt_query
    )],
    [qw(
        DEFAULT_ERROR_REDIRECT_VERSION_MISMATCH
        150
        GENERAL
        DOCUMENT_READ
        !
        Bivio::UI::HTML::ErrorPages->execute_version_mismatch
    )],
    [qw(
        CLUB_ADMIN_INVITE_DELETE
        151
        CLUB
        ADMIN_WRITE
        ?/admin/invite/delete
        Bivio::Biz::Model::RealmInviteList->execute_load_this
        Bivio::Biz::Model::DeleteInviteForm
        next=CLUB_ADMIN_INVITE_LIST
    )],
    [qw(
        CLUB_ADMIN_INVITE_RESEND
        152
        CLUB
        ADMIN_WRITE
        ?/admin/invite/resend
        Bivio::Biz::Model::RealmInvite->execute_load_this
        Bivio::Biz::Model::ResendInviteForm
        Bivio::UI::HTML::Club::ResendInvite
        next=CLUB_ADMIN_INVITE_LIST
    )],
    [qw(
        CLUB_ADMIN_GUEST_DELETE
        153
        CLUB
        ADMIN_WRITE
        ?/admin/guest/delete
        Bivio::Biz::Model::ClubUserList->execute_load_this
        Bivio::Biz::Model::DeleteGuestForm
        Bivio::UI::HTML::Club::DeleteGuest
        next=CLUB_ADMIN_USER_LIST
    )],
    [qw(
        CLUB_ADMIN_GUEST_2_MEMBER
        154
        CLUB
        ADMIN_WRITE
        ?/admin/guest2member
        Bivio::Biz::Action::NotDemoClub
        Bivio::Biz::Model::ClubUserList->execute_load_this
        Bivio::Biz::Model::Guest2MemberForm
        Bivio::UI::HTML::Club::Guest2Member
        next=CLUB_ADMIN_INVITE_LIST
        cancel=CLUB_ADMIN_USER_LIST
        help=adding-members-guests
    )],
#TODO: The privilege here is unclear.  This must be a guest.
    [qw(
        CLUB_GUEST_2_MEMBER_ACCEPT
        155
        CLUB
        ADMIN_READ
        ?/guest/make/member
        Bivio::Biz::Model::RealmInvite->execute_accept
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::Guest2MemberAcceptForm
        Bivio::UI::HTML::Club::Guest2MemberAccept
        next=CLUB_ADMIN_USER_LIST
        NOT_FOUND=REALM_INVITE_NOT_FOUND
        help=adding-members-guests
    )],
    [qw(
        CLUB_ACCOUNTING_REPORT_INVESTMENT_SALE
        156
        CLUB
        ACCOUNTING_READ&INVESTMENT_READ
        ?/accounting/reports/capital-gains-and-losses
        Bivio::Biz::Model::Lock
        Bivio::Biz::Action::ReportDate
        Bivio::Biz::Action::LocalDateHack
        Bivio::Biz::Action::ReportDateToday
        Bivio::Biz::Model::IncomeAndExpenseList->execute_load_all
        Bivio::Type::ScheduleDParams->execute_show_distributions
        Bivio::Biz::Model::InstrumentSaleList->execute_load_all
        Bivio::UI::HTML::Club::InstrumentSaleReport
        next=CLUB_ACCOUNTING_REPORT_INVESTMENT_SALE
        help=capital-gains-and-losses-report
    )],
    [qw(
        CLUB_ACCOUNTING_REPORT_INCOME_EXPENSE_STATEMENT
        157
        CLUB
        ACCOUNTING_READ&ACCOUNT_READ
        ?/accounting/reports/income-and-expense
        Bivio::Biz::Model::Lock
        Bivio::Biz::Action::ReportDate
        Bivio::Biz::Action::LocalDateHack
        Bivio::Biz::Action::ReportDateToday
        Bivio::Biz::Model::IncomeAndExpenseList->execute_load_all
        Bivio::UI::HTML::Club::IncomeAndExpenseReport
        next=CLUB_ACCOUNTING_REPORT_INCOME_EXPENSE_STATEMENT
        help=income-expense-report
    )],
    # Forces user to login and then redirects to USER_HOME
    [qw(
        MY_SITE
        158
        GENERAL
        ANY_USER
        my-site/*:pub/my_site
        Bivio::Biz::Action::MyRedirect->execute_user_site
        next=USER_HOME
    )],
    [qw(
        HELP
        159
        GENERAL
        DOCUMENT_READ
        hp/*
        Bivio::Biz::Action::HTTPDocument
    )],
    [qw(
        CLUB_ACCOUNTING_REPORT_MEMBER_ALLOCATION
        160
        CLUB
        ACCOUNTING_READ&MEMBER_READ
        ?/accounting/reports/member-tax-allocations
        Bivio::Biz::Model::Lock
        Bivio::Biz::Action::ReportDate
        Bivio::Biz::Action::LocalDateHack
        Bivio::Biz::Model::MemberAllocationList->execute_load_all
        Bivio::Biz::Model::Tax1065->execute_load_for_report_date
        Bivio::Biz::Action::ReportDateToday
        Bivio::UI::HTML::Club::MemberAllocationReport
        Bivio::UI::HTML::Club::ReportPage
        next=CLUB_ACCOUNTING_REPORT_MEMBER_ALLOCATION
        help=member-tax-allocations-report
    )],
    [qw(
        CLUB_ACCOUNTING_REPORT_MISC_INCOME_AND_DEDUCTIONS
        161
        CLUB
        ACCOUNTING_READ&ACCOUNT_READ
        ?/accounting/reports/misc-income-and-deductions
        Bivio::Biz::Model::Lock
        Bivio::Biz::Action::ReportDate
        Bivio::Biz::Action::LocalDateHack
        Bivio::Biz::Action::ReportDateToday
        Bivio::Biz::Model::PortfolioDeductionList->execute_load_all
        Bivio::Biz::Model::PortfolioIncomeList->execute_load_all
        Bivio::UI::HTML::Club::MiscIncomeAndDeductions
        next=CLUB_ACCOUNTING_REPORT_MISC_INCOME_AND_DEDUCTIONS
        help=misc-income-and-deductions-report
    )],
    [qw(
        CLUB_ACCOUNTING_TAXES
        162
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/taxes
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::TaxYearForm
        Bivio::Biz::Model::MemberAllocationList->execute_load_all
        Bivio::Biz::Model::MemberTaxList->execute_load_all_with_inactive
        Bivio::Biz::Model::ForeignTaxCountryList->execute_load_all
        Bivio::UI::HTML::Club::Taxes
        next=CLUB_ACCOUNTING_TAXES
    )],
    [qw(
        CLUB_ACCOUNTING_TAXES_F1065_OPTIONS
        163
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/taxes/f1065-options
        Bivio::Biz::Action::TargetRealm->execute_auth_realm
        Bivio::Biz::Model::F1065ParametersForm
        Bivio::UI::HTML::Club::F1065Parameters
        next=CLUB_ACCOUNTING_TAXES
        require_secure=1
    )],
    [qw(
        CLUB_ACCOUNTING_TAXES_K1_OPTIONS
        164
        CLUB
        ACCOUNTING_WRITE&MEMBER_WRITE
        ?/accounting/taxes/k1-options
        Bivio::Biz::Model::F1065K1ParametersForm
        Bivio::UI::HTML::Club::F1065K1Parameters
        next=CLUB_ACCOUNTING_TAXES
        require_secure=1
    )],
    [qw(
        CLUB_ACCOUNTING_TAXES_CHECKLIST
        165
        CLUB
        ACCOUNTING_WRITE&MEMBER_WRITE
        ?/accounting/taxes/checklist
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::TaxYearSubForm
        Bivio::Biz::Action::InactiveMemberHack
        Bivio::Biz::Model::IncomeAndExpenseList->execute_load_all
        Bivio::Biz::Model::TaxId->execute_load
        Bivio::Biz::Model::MemberAllocationList->execute_load_all
        Bivio::Biz::Model::MemberTaxList->execute_load_invalid_members
        Bivio::UI::HTML::Tax::Checklist
        next=CLUB_ACCOUNTING_TAXES_CHECKLIST
        require_secure=1
    )],
    [qw(
        CLUB_ACCOUNTING_TAXES_SCHEDULE_D
        166
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/taxes/schedule-d
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::TaxYearSubForm
        Bivio::Biz::Model::IncomeAndExpenseList->execute_load_all
        Bivio::Type::ScheduleDParams->execute_hide_distributions
        Bivio::Biz::Model::InstrumentSaleList->execute_load_all
        Bivio::Biz::Model::ScheduleDList->execute_load_all
        Bivio::UI::HTML::Tax::ScheduleD
        next=CLUB_ACCOUNTING_TAXES_SCHEDULE_D
    )],
    [qw(
        CLUB_ACCOUNTING_TAXES_INCOME
        167
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/taxes/income
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::TaxYearSubForm
        Bivio::Biz::Model::PortfolioIncomeList->execute_load_all
        Bivio::UI::HTML::Tax::PortfolioIncome
        next=CLUB_ACCOUNTING_TAXES_INCOME
    )],
    [qw(
        CLUB_ACCOUNTING_TAXES_DEDUCTIONS
        168
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/taxes/deductions
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::TaxYearSubForm
        Bivio::Biz::Model::PortfolioDeductionList->execute_load_all_no_margin
        Bivio::UI::HTML::Tax::PortfolioDeductions
        next=CLUB_ACCOUNTING_TAXES_DEDUCTIONS
    )],
    [qw(
        CLUB_ACCOUNTING_TAXES_DISTRIBUTIONS
        169
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/taxes/distributions
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::TaxYearSubForm
        Bivio::Biz::Action::LocalDateHack
        Bivio::Biz::Model::CashWithdrawalList->execute_load_all
        Bivio::Biz::Model::InstrumentWithdrawalList->execute_load_all
        Bivio::UI::HTML::Tax::MemberDistributions
        next=CLUB_ACCOUNTING_TAXES_DISTRIBUTIONS
    )],
    [qw(
        CLUB_ACCOUNTING_TAXES_ALLOCATION_METHOD
        170
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/taxes/allocation-method
        Bivio::Biz::Model::AllocationMethodForm
        Bivio::UI::HTML::Club::AllocationMethod
        next=CLUB_ADMIN_TOOLS
        help=tax-allocation-methods
    )],
    [qw(
        CLUB_ACCOUNTING_TAXES_ALLOCATIONS
        171
        CLUB
        ACCOUNTING_WRITE&MEMBER_WRITE
        ?/accounting/taxes/allocations
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::TaxYearSubForm
        Bivio::Biz::Model::MemberAllocationList->execute_load_all
        Bivio::Biz::Model::Tax1065->execute_load_for_report_date
        Bivio::UI::HTML::Club::MemberAllocationReport
        Bivio::UI::HTML::Tax::AttachmentPage
        next=CLUB_ACCOUNTING_TAXES_ALLOCATIONS
        help=tax-allocation-methods
    )],
    [qw(
        CLUB_ACCOUNTING_TAXES_MISSING_FIELDS
        172
        CLUB
        ACCOUNTING_WRITE&MEMBER_WRITE
        ?/accounting/taxes/missing-fields
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::TaxYearSubForm
        Bivio::Biz::Action::InactiveMemberHack
        Bivio::Biz::Model::IncomeAndExpenseList->execute_load_all
        Bivio::Biz::Model::TaxId->execute_load
        Bivio::Biz::Model::MemberAllocationList->execute_load_all
        Bivio::Biz::Model::MemberTaxList->execute_load_invalid_members
        Bivio::UI::HTML::Tax::Checklist
        next=CLUB_ACCOUNTING_TAXES_CHECKLIST
        require_secure=1
    )],
    # All tax views are ACCOUNTING_WRITE so only the accountant can access
    [qw(
        CLUB_ACCOUNTING_TAXES_F1065
        173
        CLUB
        ACCOUNTING_WRITE
        ?/taxes-1065/*
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::TaxYearSubForm
        Bivio::Biz::Model::MemberAllocationList->execute_load_all
        Bivio::Biz::Model::MemberTaxList->execute_load_all_with_inactive
        Bivio::Biz::Accounting::Tax->check_required_fields
        Bivio::Biz::Model::IncomeAndExpenseList->execute_load_all
        Bivio::Type::ScheduleDParams->execute_hide_distributions
        Bivio::Biz::Model::InstrumentSaleList->execute_load_all
        Bivio::Biz::Model::ScheduleDList->execute_load_all
        Bivio::Biz::Model::ForeignIncomeList->execute_load_all
        Bivio::Biz::Model::F1065Form->execute_load_all
	Bivio::UI::PDF::F1065->execute
        next=CLUB_ACCOUNTING_TAXES_F1065
        require_secure=1
    )],
    [qw(
        CLUB_ACCOUNTING_TAXES_F1065K1
        174
        CLUB
        ACCOUNTING_WRITE&MEMBER_WRITE
        ?/taxes-k1/*
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::RealmUser->execute_load_parent
        Bivio::Biz::Model::TaxYearSubForm
        Bivio::Biz::Model::MemberAllocationList->execute_load_all
        Bivio::Biz::Model::MemberTaxList->execute_load_all_with_inactive
        Bivio::Biz::Model::IncomeAndExpenseList->execute_load_all
        Bivio::Biz::Model::ForeignIncomeList->execute_load_all
        Bivio::Biz::Model::F1065K1Form->execute_load_all
	Bivio::UI::PDF::F1065K1->execute
        next=CLUB_ACCOUNTING_TAXES_F1065
        require_secure=1
    )],
    [qw(
        CLUB_ACCOUNTING_TAX99_REDIRECT
        175
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/tax99
        Bivio::Biz::Action::TaxesRedirect
    )],
    [qw(
        CLUB_ACCOUNTING_INVESTMENT_CHARGES_PAID
        176
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/investment/charges-paid:?/accounting/investment/charges_paid
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::InstrumentChargesForm
        Bivio::UI::HTML::Club::InstrumentCharges
        next=CLUB_ACCOUNTING_INVESTMENT_LIST
        help=investment-transactions
    )],
    [qw(
        MAIL_RECEIVE
        177
        GENERAL
        DOCUMENT_READ
        /_mail_receive/*
        Bivio::Biz::Model::MailReceiveForm
        next=HTTP_DOCUMENT
        NOT_FOUND=MAIL_RECEIVE_NOT_FOUND
        NO_RESOURCES=MAIL_RECEIVE_NO_RESOURCES
    )],
    [qw(
        MAIL_RECEIVE_NO_RESOURCES
        178
        GENERAL
        DOCUMENT_READ
        !
        Bivio::UI::HTML::ErrorPages->execute_mail_receive_no_resources
    )],
    [qw(
        MAIL_RECEIVE_NOT_FOUND
        179
        GENERAL
        DOCUMENT_READ
        !
        Bivio::UI::HTML::ErrorPages->execute_mail_receive_not_found
    )],
    [qw(
        USER_MAIL_RECEIVE
        180
        USER
        MAIL_WRITE
        !
        Bivio::Biz::Action::UserMailPeople
        Bivio::UI::Mail::Receive
        NOT_FOUND=MAIL_RECEIVE_NOT_FOUND
        NO_RESOURCES=MAIL_RECEIVE_NO_RESOURCES
    )],
    [qw(
        CLUB_MAIL_RECEIVE
        181
        CLUB
        MAIL_WRITE
        !
        Bivio::Biz::Action::ClubMailBoard
        Bivio::Biz::Action::ClubMailMembers
        Bivio::UI::Mail::Receive
        NOT_FOUND=MAIL_RECEIVE_NOT_FOUND
        NO_RESOURCES=MAIL_RECEIVE_NO_RESOURCES
    )],
    [qw(
        CLUB_MAIL_BOARD_RECEIVE
        182
        CLUB
        MAIL_WRITE
        !
        Bivio::Biz::Action::ClubMailBoard
        Bivio::UI::Mail::Receive
        NOT_FOUND=MAIL_RECEIVE_NOT_FOUND
        NO_RESOURCES=MAIL_RECEIVE_NO_RESOURCES
    )],
    [qw(
        CLUB_MAIL_MEMBERS_RECEIVE
        183
        CLUB
        MAIL_WRITE
        !
        Bivio::Biz::Action::ClubMailMembers
        Bivio::UI::Mail::Receive
        NOT_FOUND=MAIL_RECEIVE_NOT_FOUND
        NO_RESOURCES=MAIL_RECEIVE_NO_RESOURCES
    )],
    [qw(
        CLUB_ACCOUNTING_REPORT_SELF_PERFORMANCE_DETAIL
        184
        CLUB
        ACCOUNTING_READ&PRO_FUND_INVESTOR
        ?/accounting/reports/self-performance-detail
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::DateSpanForm
        Bivio::Biz::Model::RealmUser->execute_auth_user
        Bivio::Biz::Model::MemberPerformanceDetailList->execute_load_all
        Bivio::UI::HTML::Club::MemberPerformanceDetailReport
        next=CLUB_ACCOUNTING_REPORT_MEMBER_PERFORMANCE_DETAIL
        help=member-performance-detail-report
        NOT_FOUND=CLUB_ACCOUNTING_REPORT_MEMBER_PERFORMANCE
    )],
        # CLUB_MAIL_ADMIN_RECEIVE has permission LOGIN
        # (and not MAIL_WRITE) so that there are no restrictions
        # on who can send a message to <club>-owner. Even if a club
        # has restricted mail permissions, any bounces have to be
        # accepted and must not cause an additional bounce.
    [qw(
        CLUB_MAIL_ADMIN_RECEIVE
        185
        CLUB
        LOGIN
        !
        Bivio::Biz::Action::ClubMailAdmin
        Bivio::UI::Mail::Receive
        NOT_FOUND=MAIL_RECEIVE_NOT_FOUND
        NO_RESOURCES=MAIL_RECEIVE_NO_RESOURCES
    )],
    [qw(
        CLUB_MEMBER_OPEN_BALANCE
        186
        CLUB
        ACCOUNTING_WRITE&MEMBER_WRITE&ADMIN_WRITE
        ?/accounting/members/openbal
        Bivio::Biz::Action::NotDemoClub
        Bivio::Biz::Model::MemberOpenBalanceList->execute_load_all
        Bivio::Biz::Model::MemberOpenBalanceListForm
        Bivio::UI::HTML::Club::MemberOpenBalanceList
        next=CLUB_ADMIN_SHADOW_MEMBER_INVITE
        help=opening-balance
    )],
    [qw(
        CLUB_INVESTMENT_OPEN_BALANCE
        187
        CLUB
        ACCOUNTING_WRITE&ADMIN_WRITE
        ?/accounting/investments/openbal
        Bivio::Biz::Action::NotDemoClub
        Bivio::Biz::Model::InstrumentOpenBalanceList->execute_load_all
        Bivio::Biz::Model::InstrumentOpenBalanceListForm
        Bivio::UI::HTML::Club::InstrumentOpenBalanceList
        next=CLUB_MEMBER_OPEN_BALANCE
        help=opening-balance
    )],
    [qw(
        CLUB_OPEN_BALANCE
        188
        CLUB
        ACCOUNTING_WRITE&ADMIN_WRITE
        ?/accounting/opening-balance:?/accounting/opening_balance
        Bivio::Biz::Action::NotDemoClub
        Bivio::Biz::Model::AccountOpenBalanceList->execute_load_all
        Bivio::Biz::Model::AccountOpenBalanceListForm
        Bivio::UI::HTML::Club::AccountOpenBalance
        next=CLUB_INVESTMENT_OPEN_BALANCE
        cancel=CLUB_ADMIN_TOOLS
        help=opening-balance
    )],
    [qw(
        CLUB_MAIL_DELETE
        189
        CLUB
        MAIL_ADMIN
        ?/mail/delete
        Bivio::Biz::Action::PublicRealm
        Bivio::Biz::Model::MailList->execute_load_this
        Bivio::Biz::Action::ClubMailDelete
        next=CLUB_COMMUNICATIONS_MAIL_LIST
        help=mail
    )],
    [qw(
        CLUB_ACCOUNTING_MEMBER_WITHDRAWAL
        190
        CLUB
        ACCOUNTING_WRITE&MEMBER_WRITE
        ?/accounting/member/withdrawal
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::MemberList->execute_load_all_active
        Bivio::Biz::Model::RealmAccountList->execute_load_valuation_only
        Bivio::Biz::Model::MemberWithdrawalForm
        Bivio::Biz::Model::AccountSummaryList->execute_load_valuation_only
        Bivio::UI::HTML::Club::MemberWithdrawal
        next=CLUB_ACCOUNTING_MEMBER_LIST
        help=member-transactions
    )],
    [qw(
        CLUB_ACCOUNTING_MEMBER_WITHDRAWAL_CONFIRM
        191
        CLUB
        ACCOUNTING_WRITE&MEMBER_WRITE
        ?/accounting/member/withdrawal/confirm
        Bivio::Biz::Model::RealmUserList->execute_load_this
        Bivio::Biz::Action::TargetRealm->execute_this_member
        Bivio::Biz::Model::MemberWithdrawalConfirmForm
        Bivio::UI::HTML::Club::MemberWithdrawalConfirm
        next=CLUB_ACCOUNTING_MEMBER_LIST
        help=member-transactions
    )],
    [qw(
        CLUB_ADMIN_MEMBER_DELETE
        192
        CLUB
        ADMIN_WRITE&MEMBER_WRITE
        ?/admin/member/delete
        Bivio::Biz::Model::ClubUserList->execute_load_this
        Bivio::Biz::Model::DeleteMemberForm
        Bivio::UI::HTML::Club::DeleteMember
        next=CLUB_ADMIN_USER_LIST
    )],
#TODO: These permissions are "wrong" in that you need, not write, but
#      everybody has read and this means people could read the ssns
#      of people such as guests.  Don't want this.
    [qw(
        CLUB_ADMIN_EXPORT
        193
        CLUB
	ACCOUNTING_WRITE&ADMIN_WRITE&MEMBER_WRITE
        ?/admin/export
	Bivio::UI::HTML::Club::Export
        help=exporting-club-data
    )],
    [qw(
        CLUB_ADMIN_EXPORT_COMPRESSED
        194
        CLUB
	ACCOUNTING_WRITE&ADMIN_WRITE&MEMBER_WRITE
        ?/admin/clubexp.xml.zip
        Bivio::Biz::Model::Lock
        Bivio::UI::XML::ClubExport->execute_compressed
        require_secure=1
    )],
    [qw(
        CLUB_ADMIN_EXPORT_PLAIN
        195
        CLUB
        ACCOUNTING_WRITE&ADMIN_WRITE&MEMBER_WRITE
        ?/admin/clubexp.xml
        Bivio::Biz::Model::Lock
        Bivio::UI::XML::ClubExport->execute_plain
        require_secure=1
    )],
    [qw(
        CLUB_ACCOUNTING_REPORT_MEMBER_STATUS
        196
        CLUB
        ACCOUNTING_READ&MEMBER_READ
        ?/accounting/reports/member-status
        Bivio::Biz::Model::Lock
        Bivio::Biz::Action::ReportDate
        Bivio::Biz::Action::LocalDateHack
        Bivio::Biz::Model::MemberStatusDateForm
        Bivio::Biz::Model::MemberStatusList->execute_load_all_with_inactive
        Bivio::UI::HTML::Club::MemberStatusReport
        next=CLUB_ACCOUNTING_REPORT_MEMBER_STATUS
        help=member-status-report
    )],
    [qw(
        USER_MAIL_POST
        197
        USER
        MAIL_POST&ANY_USER
        ?/mail/post
        Bivio::Biz::Action::PublicRealm
        Bivio::Biz::Model::MailPostForm
        Bivio::Biz::Model::MailToList->execute_load_all
        Bivio::UI::HTML::User::MailPost
        next=HTTP_DOCUMENT
    )],
    [qw(
        CLUB_MAIL_POST
        198
        CLUB
        MAIL_POST&MAIL_READ
        ?/mail/post
        Bivio::Biz::Action::PublicRealm
        Bivio::Biz::Model::MailPostForm
        Bivio::Biz::Model::MailToList->execute_load_all
        Bivio::UI::HTML::Club::MailPost
        next=CLUB_COMMUNICATIONS_MAIL_LIST
        help=mail
    )],
    [qw(
        CLUB_MAIL_REPLY
        199
        CLUB
        MAIL_POST&MAIL_READ
        ?/mail/reply
        Bivio::Biz::Action::PublicRealm
        Bivio::Biz::Model::MailList->execute_load_this
        Bivio::Biz::Model::MailPartList->execute_load_all
        Bivio::Biz::Model::MailReplyForm
        Bivio::Biz::Model::MailToList->execute_load_all
        Bivio::UI::HTML::Club::MailReply
        next=CLUB_COMMUNICATIONS_MAIL_LIST
        help=mail
    )],
    [qw(
        CLUB_MAIL_FORWARD
        200
        CLUB
        MAIL_FORWARD
        ?/mail/forward
        Bivio::Biz::Action::PublicRealm
        Bivio::Biz::Model::MailList->execute_load_this
        Bivio::Biz::Model::MailForwardForm
        Bivio::UI::HTML::Club::MailForward
        next=CLUB_COMMUNICATIONS_MAIL_LIST
        help=mail
    )],
    [qw(
        GENERAL_SEARCH
        201
        GENERAL
        DOCUMENT_READ
        pub/search
        Bivio::Biz::Action::PublicRealm
        Bivio::Biz::Model::SearchList->execute_load_page
        Bivio::UI::HTML::Common::SearchList
        next=HTTP_DOCUMENT
    )],
    [qw(
        CLUB_SEARCH
        202
        CLUB
        DOCUMENT_READ
        ?/search
        Bivio::Biz::Action::PublicRealm
        Bivio::Biz::Model::SearchList->execute_load_page
        Bivio::UI::HTML::Common::SearchList
        next=HTTP_DOCUMENT
    )],
    [qw(
        CLUB_ACCOUNTING_MEMBER_WITHDRAWAL_STOCK
        203
        CLUB
        ACCOUNTING_WRITE&MEMBER_WRITE
        ?/accounting/member/withdrawal-stock
        Bivio::Biz::Model::Lock
        Bivio::Biz::Action::ReportDate
        Bivio::Biz::Action::LocalDateHack
        Bivio::Biz::Model::InstrumentSummaryList->execute_load_all_active
        Bivio::Biz::Model::MemberInstrumentWithdrawalListForm
        Bivio::UI::HTML::Club::MemberInstrumentWithdrawalList
        next=CLUB_ACCOUNTING_MEMBER_LIST
        help=member-transactions
    )],
    [qw(
        CLUB_ACCOUNTING_INVESTMENT_LOT_LIST
        204
        CLUB
        ACCOUNTING_WRITE&MEMBER_WRITE
        ?/accounting/investment/lot-list
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::RealmInstrument->execute_load_parent
        Bivio::Biz::Model::RealmInstrumentLotList->execute_load_all
        Bivio::Biz::Model::RealmInstrumentLotListForm
        Bivio::UI::HTML::Club::RealmInstrumentLotList
        next=CLUB_ACCOUNTING_INVESTMENT_LIST
        help=investment-lots
        want_query=1
    )],
    [qw(
        CLUB_ACCOUNTING_REPORT_MEMBER_WITHDRAWAL_LIST
        205
        CLUB
        ACCOUNTING_READ&MEMBER_READ
        ?/accounting/reports/withdrawals
        Bivio::Biz::Model::MemberWithdrawalList->execute_load_all
        Bivio::UI::HTML::Club::MemberWithdrawalReportList
        help=member-withdrawal-summary
    )],
    [qw(
        CLUB_ACCOUNTING_REPORT_MEMBER_WITHDRAWAL
        206
        CLUB
        ACCOUNTING_READ&MEMBER_READ
        ?/accounting/reports/withdrawal
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::Entry->execute_load_parent
        Bivio::Biz::Model::MemberEntry->execute_load_parent
        Bivio::Biz::Model::MemberWithdrawalInfo->execute_load_all
        Bivio::UI::HTML::Club::MemberWithdrawalReport
        next=CLUB_ACCOUNTING_REPORT_MEMBER_WITHDRAWAL
        help=member-withdrawal-report
    )],
    [qw(
        DEFAULT_ERROR_REDIRECT_MISSING_COOKIES
        207
        GENERAL
        DOCUMENT_READ
        !
        Bivio::UI::HTML::ErrorPages->execute_missing_cookies
        help=enabling-cookies
    )],
    [qw(
        REALM_INVITE_WRONG_USER
        208
        GENERAL
        DOCUMENT_READ
        !
        Bivio::UI::HTML::ErrorPages->execute_realm_invite_wrong_user
    )],
    [qw(
        CLUB_ACCOUNTING_REPORT_INVESTMENT_PERFORMANCE
        209
        CLUB
        ACCOUNTING_READ&INVESTMENT_READ
        ?/accounting/reports/investment-performance
        Bivio::Biz::Model::Lock
        Bivio::Type::UserPreference->execute_show_inactive_instruments
        Bivio::Biz::Model::DateSpanForm
        Bivio::Biz::Model::InstrumentPerformanceList->execute_load_all
        Bivio::UI::HTML::Club::InstrumentPerformanceReport
        next=CLUB_ACCOUNTING_REPORT_INVESTMENT_PERFORMANCE
        help=investment-performance-report
    )],
    [qw(
        CLUB_ACCOUNTING_REPORT_INVESTMENT_PERFORMANCE_DETAIL
        210
        CLUB
        ACCOUNTING_READ&INVESTMENT_READ
        ?/accounting/reports/investment-performance-detail
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::InstrumentDateSpanForm
        Bivio::Biz::Model::RealmInstrumentList->execute_load_all
        Bivio::Biz::Model::InstrumentPerformanceDetailList->execute_load_all
        Bivio::UI::HTML::Club::InstrumentPerformanceDetailReport
        next=CLUB_ACCOUNTING_REPORT_INVESTMENT_PERFORMANCE_DETAIL
        help=investment-performance-detail-report
        NOT_FOUND=CLUB_ACCOUNTING_REPORT_INVESTMENT_PERFORMANCE
    )],
    [qw(
        CLUB_ADMIN_PUBLIC
        211
        CLUB
        REALM_PUBLICIZE
        ?/admin/public
        Bivio::Biz::Action::PublicRealm
        Bivio::Biz::Action::TargetRealm->execute_auth_realm
        Bivio::Biz::Action::NotDemoClub
        Bivio::Biz::Model::PublicRealmForm
        Bivio::UI::HTML::Club::PublicRealm
        next=CLUB_ADMIN_TOOLS
        help=public-access
    )],
    [qw(
        CLUB_ADMIN_PRIVATE
        212
        CLUB
        ADMIN_WRITE
        ?/admin/private
        Bivio::Biz::Action::PublicRealm
        Bivio::Biz::Action::NotDemoClub
        Bivio::Biz::Model::PrivateRealmForm
        Bivio::UI::HTML::Club::PrivateRealm
        next=CLUB_ADMIN_TOOLS
        help=public-access
    )],
    [qw(
        CLUB_INTRO
        213
        CLUB
        DOCUMENT_READ
        ?/intro
        Bivio::Biz::Action::PublicRealm
        Bivio::UI::HTML::Club::Home
    )],
    [qw(
        CLUB_ACCOUNTING_REPORT_MEMBER_PERFORMANCE
        214
        CLUB
        ACCOUNTING_READ&MEMBER_READ
        ?/accounting/reports/member-performance
        Bivio::Biz::Model::Lock
        Bivio::Type::UserPreference->execute_show_inactive_members
        Bivio::Biz::Model::DateSpanForm
        Bivio::Biz::Model::MemberPerformanceList->execute_load_all_with_inactive_and_no_units
        Bivio::UI::HTML::Club::MemberPerformanceReport
        next=CLUB_ACCOUNTING_REPORT_MEMBER_PERFORMANCE
        help=member-performance-report
    )],
    [qw(
        CLUB_ACCOUNTING_REPORT_MEMBER_PERFORMANCE_DETAIL
        215
        CLUB
        ACCOUNTING_READ&MEMBER_READ
        ?/accounting/reports/member-performance-detail
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::MemberDateSpanForm
        Bivio::Biz::Model::AllMemberList->execute_load_all_with_inactive
        Bivio::Biz::Model::MemberPerformanceDetailList->execute_load_all
        Bivio::UI::HTML::Club::MemberPerformanceDetailReport
        next=CLUB_ACCOUNTING_REPORT_MEMBER_PERFORMANCE_DETAIL
        help=member-performance-detail-report
        NOT_FOUND=CLUB_ACCOUNTING_REPORT_MEMBER_PERFORMANCE
    )],
    [qw(
        DEFAULT_ERROR_REDIRECT_CORRUPT_FORM
        216
        GENERAL
        DOCUMENT_READ
        !
        Bivio::UI::HTML::ErrorPages->execute_corrupt_form
    )],
    [qw(
        CLUB_HEADING_AS_FRAME
        217
        CLUB
        DOCUMENT_READ
        ?/heading-frame
        Bivio::Biz::Action::PublicRealm
        Bivio::UI::HTML::Common::HomePage->execute_frame
    )],
    [qw(
        PUBLIC_CLUBS
        218
        GENERAL
        ADMIN_WRITE
        adm/clubs
        Bivio::Biz::Model::PublicClubList->execute_load_all_with_query
        Bivio::UI::HTML::General::PublicClubs
    )],
    [qw(
        CLUB_COMMUNICATIONS_FILE_RENAME
        219
        CLUB
        DOCUMENT_WRITE
        ?/file-rename/*
        Bivio::Biz::Model::Lock
        Bivio::Biz::Action::PublicRealm
        Bivio::Type::FileVolume->execute_file
        Bivio::Biz::Model::FilePathList
        Bivio::Biz::Model::FileDirectoryList->execute_load_all
        Bivio::Biz::Model::FileRenameForm
        Bivio::UI::HTML::Widget::FilePageHeading->execute_no_links
        Bivio::UI::HTML::Club::FileRename
        next=CLUB_COMMUNICATIONS_FILE_READ
        help=files
    )],
    #220
    [qw(
        ASK_CANDIS_MESSAGE_LIST_REDIRECT
        221
        GENERAL
        DOCUMENT_READ
        pub/ask_candis
        Bivio::Biz::Action::CelebrityRedirect
        next=CLUB_HOME
    )],
    [qw(
        ASK_CANDIS_MESSAGE_DETAIL_REDIRECT
        222
        GENERAL
        DOCUMENT_READ
        pub/ask_candis/msg
        Bivio::Biz::Action::CelebrityRedirect
        next=CLUB_COMMUNICATIONS_MAIL_DETAIL
    )],
    [qw(
        TREZ_TALK_MESSAGE_LIST_REDIRECT
        223
        GENERAL
        DOCUMENT_READ
        pub/trez_talk
        Bivio::Biz::Action::CelebrityRedirect
        next=CLUB_HOME
    )],
    [qw(
        TREZ_TALK_MESSAGE_DETAIL_REDIRECT
        224
        GENERAL
        DOCUMENT_READ
        pub/trez_talk/msg
        Bivio::Biz::Action::CelebrityRedirect
        next=CLUB_COMMUNICATIONS_MAIL_DETAIL
    )],
    [qw(
        CLUB_COMMUNICATIONS_FILE_UNZIP
        225
        CLUB
        DOCUMENT_WRITE
        ?/file-unzip/*
        Bivio::Biz::Model::Lock
        Bivio::Biz::Action::PublicRealm
        Bivio::Type::FileVolume->execute_file
        Bivio::Biz::Model::FilePathList
        Bivio::Biz::Model::FileDirectoryList->execute_load_all
        Bivio::Biz::Model::FileUnzipForm
        Bivio::UI::HTML::Widget::FilePageHeading->execute_no_links
        Bivio::UI::HTML::Club::FileUnzip
        next=CLUB_COMMUNICATIONS_FILE_READ
        help=files
    )],
    [qw(
        CLUB_ACCOUNTING_INVESTMENT_MERGER
        226
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/investment/merger
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::RealmAccountList->execute_load_valuation_only
        Bivio::Biz::Model::InstrumentMergerForm
        Bivio::UI::HTML::Club::InstrumentMerger
        next=CLUB_ACCOUNTING_INVESTMENT_LIST
        help=investment-transactions
    )],
    [qw(
        CLUB_ACCOUNTING_INVESTMENT_SPINOFF
        227
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/investment/spin-off
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::RealmAccountList->execute_load_valuation_only
        Bivio::Biz::Model::InstrumentSpinoffForm
        Bivio::UI::HTML::Club::InstrumentSpinoff
        next=CLUB_ACCOUNTING_INVESTMENT_LIST
        help=investment-transactions
    )],
    [qw(
        CLUB_ACCOUNTING_INVESTMENT_REINVEST
        228
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/investment/reinvest
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::InstrumentReinvestForm
        Bivio::UI::HTML::Club::InstrumentReinvest
        next=CLUB_ACCOUNTING_INVESTMENT_LIST
        help=investment-transactions
    )],
    [qw(
        CLUB_ACCOUNTING_INVESTMENT_SPINOFF_BASIS
        230
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/investment/basis-calculator
        Bivio::Biz::Model::SpinoffBasisForm
        Bivio::UI::HTML::Club::SpinoffBasis
        next=CLUB_ACCOUNTING_INVESTMENT_LIST
        help=investment-transactions
    )],
    [qw(
        CLUB_ACCOUNTING_TRANSACTION_EDIT
        231
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/edit
        Bivio::Biz::Model::ContextRedirectForm
        Bivio::Biz::Action::EditTransaction
        next=CLUB_ACCOUNTING_TRANSACTION_EDIT
    )],
    [qw(
        CLUB_ACCOUNTING_INVESTMENT_DELETE
        232
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/investment/detail/delete
        Bivio::Biz::Model::RealmInstrument->execute_load_this
        Bivio::Biz::Action::InstrumentDelete
    )],
    [qw(
        CLUB_ACCOUNTING_LEGACY_EDIT_FAILURE
        233
        CLUB
        DOCUMENT_READ
        !
        Bivio::UI::HTML::ErrorPages->execute_club_accounting_legacy_edit_failure
    )],
    [qw(
        CLUB_ACCOUNTING_INSTRUMENT_DELETE_FAILURE
        234
        CLUB
        DOCUMENT_READ
        !
        Bivio::UI::HTML::ErrorPages->execute_club_accounting_instrument_delete_failure
    )],
    [qw(
        ADM_FIND_REALM_OWNER
        235
        GENERAL
        ADMIN_WRITE
        adm/lookup
        Bivio::Biz::Model::AdmFindRealmOwnerForm
        Bivio::UI::HTML::Adm::FindRealmOwner
        next=HTTP_DOCUMENT
        require_secure=1
    )],
    [qw(
        USER_ADMIN_PREFERENCES_EDIT
        236
        USER
        ADMIN_WRITE
        ?/admin/edit/preferences
        Bivio::Biz::Model::EditPreferencesForm
        Bivio::UI::HTML::User::EditPreferences
        next=USER_ADMIN_PREFERENCES_EDIT
        help=change-preferences
        require_context=0
    )],
    [qw(
	CLUB_ACCOUNTING_REPORT_COMPLETE_JOURNAL
	237
        CLUB
        ACCOUNTING_READ&MEMBER_READ&ACCOUNT_READ&INVESTMENT_READ
        ?/accounting/reports/journal
        Bivio::Biz::Model::Lock
        Bivio::Biz::Action::ReportDate
        Bivio::Biz::Action::LocalDateHack
        Bivio::Biz::Model::CompleteJournalDateForm
        Bivio::Biz::Model::CompleteJournalList->execute_load_all
	Bivio::UI::HTML::Club::CompleteJournal
        next=CLUB_ACCOUNTING_REPORT_COMPLETE_JOURNAL
        help=journal-report
    )],
    [qw(
        CLUB_ACCOUNTING_REPORT_BALANCE_SHEET
        238
        CLUB
        ACCOUNTING_READ&ACCOUNT_READ
        ?/accounting/reports/balance-sheet
        Bivio::Biz::Model::Lock
        Bivio::Biz::Action::ReportDate
        Bivio::Biz::Action::LocalDateHack
        Bivio::Biz::Action::ReportDateToday
        Bivio::Biz::Model::BalanceSheetList->execute_load_all
        Bivio::UI::HTML::Club::BalanceSheet
        next=CLUB_ACCOUNTING_REPORT_BALANCE_SHEET
        help=balance-sheet-report
    )],
    [qw(
	CLUB_ACCOUNTING_REPORT_TRANSACTION_HISTORY
	239
        CLUB
        ACCOUNTING_READ&MEMBER_READ&ACCOUNT_READ&INVESTMENT_READ
        ?/accounting/reports/transaction-history
        Bivio::Biz::Model::Lock
        Bivio::Biz::Action::ReportDate
        Bivio::Biz::Action::LocalDateHack
        Bivio::Biz::Model::TransactionSummaryDateForm
        Bivio::Biz::Action::TransactionSummary
	Bivio::UI::HTML::Club::TransactionSummary
        next=CLUB_ACCOUNTING_REPORT_TRANSACTION_HISTORY
        help=transaction-history-report
    )],
    [qw(
        CLUB_ACCOUNTING_REALM_ACCOUNT_EDIT
        240
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/account/edit
        Bivio::Biz::Model::RealmAccountForm
        Bivio::UI::HTML::Club::RealmAccount
        next=CLUB_ACCOUNTING_ACCOUNT_LIST
        require_secure=1
    )],
    [qw(
        CLUB_ACCOUNTING_REALM_ACCOUNT_DELETE
        242
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/account/detail/delete
        Bivio::Biz::Model::RealmAccount->execute_load_this
        Bivio::Biz::Model::RealmAccountList->execute_load_valuation_only
        Bivio::Biz::Action::RealmAccountDelete
    )],
    # Name must have USER_ADMIN_PREFERENCES_EDIT.  See Widget::EditPreferences
    [qw(
        USER_ADMIN_PREFERENCES_EDIT_WITH_CONTEXT
        243
        USER
        ADMIN_WRITE
        ?/admin/edit/preferences/internal
        Bivio::Biz::Model::EditPreferencesForm
        Bivio::UI::HTML::User::EditPreferences
        next=USER_ADMIN_PREFERENCES_EDIT
        help=change-preferences
    )],
    [qw(
        CLUB_ACCOUNTING_REALM_ACCOUNT_CREATE
        244
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/account/create
        Bivio::Biz::Model::RealmAccountForm
        Bivio::UI::HTML::Club::RealmAccount
        next=CLUB_ACCOUNTING_ACCOUNT_LIST
        want_query=0
        help=creating-accounts
     )],
    #245
    #246
    [qw(
        CLUB_ACCOUNTING_TAXES_FOREIGN_INCOME
        247
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/taxes/foreign-income
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::TaxYearSubForm
        Bivio::Biz::Model::ForeignIncomeList->execute_load_all
        Bivio::UI::HTML::Tax::ForeignIncome
        next=CLUB_ACCOUNTING_TAXES_FOREIGN_INCOME
    )],
    [qw(
        CLUB_SETUP_AGE
        248
        CLUB
        ADMIN_READ
        ?/age
        Bivio::Biz::Model::RealmUser->execute_auth_user
        Bivio::UI::HTML::Club::New
    )],
    # All tax views are ACCOUNTING_WRITE so only the accountant can access
    [qw(
        CLUB_ACCOUNTING_TAXES_SCHEDULE_D_PDF
        249
        CLUB
        ACCOUNTING_WRITE
        ?/accounting/taxes/schedule-d.pdf
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::TaxYearSubForm
        Bivio::Biz::Model::IncomeAndExpenseList->execute_load_all
        Bivio::Type::ScheduleDParams->execute_hide_distributions
        Bivio::Biz::Model::InstrumentSaleList->execute_load_all
        Bivio::Biz::Model::ScheduleDList->execute_load_all
        Bivio::UI::PDF::ScheduleD
        next=CLUB_ACCOUNTING_TAXES_SCHEDULE_D_PDF
    )],
    [qw(
        CLUB_SETUP_ACCOUNTING
        250
        CLUB
        ADMIN_READ
        ?/setup-accounting
        Bivio::Biz::Model::RealmUser->execute_auth_user
        Bivio::UI::HTML::Club::New
    )],
    #251
    [qw(
        PASSWORD_FORGOTTEN
        252
        GENERAL
        DOCUMENT_READ
        pub/lost-password
        Bivio::Biz::Model::PasswordRequestForm
        Bivio::UI::HTML::General::ForgotPassword
        next=PASSWORD_AUTHORIZATION_SENT
    )],
    [qw(
        PASSWORD_AUTHORIZATION_SENT
        253
        GENERAL
        DOCUMENT_READ
        pub/sent-password
        Bivio::UI::HTML::General::ForgotPasswordConfirmation
    )],
    [qw(
        PASSWORD_RESET
        254
        GENERAL
        DOCUMENT_READ
        pub/reset-password
        Bivio::Biz::Model::PasswordRequest->execute_load_from_query
        Bivio::Biz::Model::PasswordForm
        Bivio::UI::HTML::User::EditPassword
        next=MY_CLUB_SITE
        cancel=HTTP_DOCUMENT
        NOT_FOUND=PASSWORD_REQUEST_NOT_FOUND
        require_context=0
    )],
    [qw(
        PASSWORD_REQUEST_NOT_FOUND
        255
        GENERAL
        DOCUMENT_READ
        !
        Bivio::UI::HTML::ErrorPages->execute_password_request_not_found
    )],
    [qw(
        ACCOUNT_SYNC_PROCESS_ALL
        256
        GENERAL
        DOCUMENT_READ
        _job/account_sync_process_all
        Bivio::Biz::Action::AccountSyncProcessAll
    )],
    [qw(
        ADM_REALM_NOTICE_LIST
        257
        GENERAL
        ADMIN_WRITE
        adm/notices
        Bivio::Biz::Model::AdmRealmNoticeList->execute_load_page
	Bivio::UI::HTML::Adm::RealmNoticeList
        require_secure=1
    )],
    [qw(
        ADM_REALM_NOTICE_DELETE
        258
        GENERAL
        ADMIN_WRITE
        adm/notice/delete
        Bivio::Biz::Model::AdmRealmNoticeList->execute_load_this
        Bivio::Biz::Model::RealmNotice->execute_unauth_delete_this
        Bivio::Biz::Action::ClientRedirect->execute_next
        next=ADM_REALM_NOTICE_LIST
        require_secure=1
    )],
    [qw(
        ADM_REALM_NOTICE_CREATE
        259
        GENERAL
        ADMIN_WRITE
        adm/notice/create
        Bivio::Biz::Model::AdmRealmNoticeForm
        Bivio::UI::HTML::Adm::CreateRealmNotice
        next=ADM_REALM_NOTICE_LIST
        require_secure=1
    )],
    [qw(
        CLUB_ACCOUNTING_MEMBER_ADJUSTMENT
        260
        CLUB
        ACCOUNTING_WRITE&MEMBER_WRITE&SUPER_USER_TRANSIENT
        ?/accounting/member/adjustment
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::RealmUserList->execute_load_this
        Bivio::Biz::Action::TargetRealm->execute_this_member_or_withdrawn
        Bivio::Biz::Model::MemberAdjustmentForm
        Bivio::UI::HTML::Club::MemberAdjustment
        next=CLUB_ACCOUNTING_MEMBER_LIST
    )],
    [qw(
        CLUB_ACCOUNTING_ACCOUNT_ADJUSTMENT
        261
        CLUB
        ACCOUNTING_WRITE&SUPER_USER_TRANSIENT
        ?/accounting/account/adjustment
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::RealmAccount->execute_load_parent
        Bivio::Biz::Model::AccountAdjustmentForm
        Bivio::UI::HTML::Club::AccountAdjustment
        next=CLUB_ACCOUNTING_ACCOUNT_LIST
    )],
    [qw(
        CLUB_ACCOUNTING_INVESTMENT_ADJUSTMENT
        262
        CLUB
        ACCOUNTING_WRITE&SUPER_USER_TRANSIENT
        ?/accounting/investment/adjustment
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::RealmInstrument->execute_load_parent
        Bivio::Biz::Model::InstrumentAdjustmentForm
        Bivio::UI::HTML::Club::InstrumentAdjustment
        next=CLUB_ACCOUNTING_INVESTMENT_LIST
    )],
    [qw(
        CLUB_ADMIN_EC_ACCOUNT_SYNC_DONE
        263
        CLUB
        ADMIN_READ
        ?/admin/subscribe/account-sync/setup
        Bivio::Biz::Model::RealmAccountList->execute_load_valuation_only
        Bivio::Biz::Model::AccountSyncForm
        Bivio::UI::HTML::Club::ECAccountSyncDone
        next=CLUB_ACCOUNTING_REALM_ACCOUNT_EDIT
        require_secure=1
    )],
    [qw(
        CLUB_ADMIN_MEMBER_TAKE_OFFLINE
        264
        CLUB
        ADMIN_READ&MEMBER_READ
        ?/admin/member/take-offline
        Bivio::Biz::Model::ClubUserList->execute_load_this
        Bivio::Biz::Model::MemberOfflineForm
        Bivio::UI::HTML::Club::MemberTakeOffline
        next=CLUB_ADMIN_USER_LIST
        help=taking-offline
    )],
    [qw(
        MEMBER_OFFLINE_CONFIRMATION
        265
        USER
        DOCUMENT_READ
        ?/offline
        Bivio::UI::HTML::User::MemberOfflineConfirmation
    )],
    [qw(
        CLUB_ADM_DELETE
        266
        CLUB
        ADMIN_WRITE&SUPER_USER_TRANSIENT
        ?/adm/delete
        Bivio::Biz::Model::ClubDeleteForm
        Bivio::UI::HTML::Club::Delete
        next=USER_HOME
    )],
    [qw(
        ADM_MERGER_SPINOFF_LIST
        267
        GENERAL
        ADMIN_WRITE
        adm/merger-spinoff
        Bivio::Biz::Model::AdmInstrumentMergerSpinoffList->execute_load_page
        Bivio::UI::HTML::Adm::InstrumentMergerSpinoffList
        require_secure=1
    )],
    [qw(
        ADM_MERGER_SPINOFF_DELETE
        268
        GENERAL
        ADMIN_WRITE
        adm/merger-spinoff/delete
        Bivio::Biz::Model::AdmInstrumentMergerSpinoffList->execute_load_this
        Bivio::Biz::Action::InstrumentMergerSpinoffDelete
        Bivio::Biz::Action::ClientRedirect->execute_next_stateless
        next=ADM_MERGER_SPINOFF_LIST
        require_secure=1
    )],
    [qw(
        ADM_MERGER_SPINOFF_CREATE
        269
        GENERAL
        ADMIN_WRITE
        adm/merger-spinoff/create
        Bivio::Biz::Model::AdmInstrumentMergerSpinoffForm
        Bivio::UI::HTML::Adm::CreateInstrumentMergerSpinoff
        next=ADM_MERGER_SPINOFF_LIST
        require_secure=1
    )],
    [qw(
        CLUB_ADMIN_MEMBER_MERGE
        270
        CLUB
        ADMIN_WRITE&SUPER_USER_TRANSIENT
        ?/adm/merge-member
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::ClubUserList->execute_load_this
        Bivio::Biz::Model::MemberList->execute_load_all
        Bivio::Biz::Model::MemberMergeForm
        Bivio::UI::HTML::Club::MemberMerge
        next=CLUB_ADMIN_USER_LIST
    )],
    # Would redirect to bivio home page but want imagemenu bar?
    [qw(
        USER_ADM_DELETE
        271
        USER
        ADMIN_WRITE&SUPER_USER_TRANSIENT
        ?/adm/delete
        Bivio::Biz::Model::Lock
        Bivio::Biz::Model::UserDeleteForm
        Bivio::UI::HTML::User::Delete
        next=HTTP_DOCUMENT
    )],
    [qw(
        ADM_SPLIT_LIST
        272
        GENERAL
        ADMIN_WRITE
        adm/splits
        Bivio::Biz::Model::AdmInstrumentSplitList->execute_load_page
        Bivio::UI::HTML::Adm::InstrumentSplitList
        require_secure=1
    )],
    [qw(
        ADM_QUOTES
        273
        GENERAL
        ADMIN_WRITE
        adm/quotes
        Bivio::Biz::Model::AdmQuoteList->execute_load_page
        Bivio::UI::HTML::Adm::QuoteList
        require_secure=1
    )],
    [qw(
        ADM_FIND_REALM_OWNER_LIST
        274
        GENERAL
        ADMIN_WRITE
        adm/lookup-new
        Bivio::Biz::Model::AdmLookupForm
        Bivio::UI::HTML::Adm::LookupList
        next=HTTP_DOCUMENT
        require_secure=1
    )],
    [qw(
        CLUB_ADM_ACCOUNT_SYNC_ALL
        275
        CLUB
        ACCOUNTING_WRITE&SUPER_USER_TRANSIENT
        ?/adm/account-sync-all
        Bivio::Biz::Action::AdmAccountSync
        Bivio::Biz::Action::ClientRedirect->execute_next
        next=CLUB_ACCOUNTING_ACCOUNT_LIST
    )],
    [qw(
        CLUB_COMMUNICATIONS_MAIL_EXPANDED_LIST
        276
        CLUB
        MAIL_READ
        ?/mail-expanded
        Bivio::Biz::Action::PublicRealm
        Bivio::Biz::Model::MailExpandedList->execute_load_page
        Bivio::Biz::Model::MailExpandedListForm->execute_if_allowed
        Bivio::UI::HTML::Club::MailExpandedList
        next=CLUB_COMMUNICATIONS_MAIL_EXPANDED_LIST
        help=mail
    )],
    [qw(
        CLUB_COMMUNICATIONS_MAIL_EXPANDED_DETAIL
        277
        CLUB
        MAIL_READ
        ?/mail-expanded-msg
        Bivio::Biz::Action::PublicRealm
        Bivio::Biz::Model::MailExpandedList->execute_load_this
        Bivio::Biz::Model::MailPartList->execute_load_all
        Bivio::UI::HTML::Club::MailDetail
        help=mail
    )],
    [qw(
        CLUB_COMMUNICATIONS_MAIL_COLLAPSED_LIST
        278
        CLUB
        MAIL_READ
        ?/mail-collapsed
        Bivio::Biz::Action::PublicRealm
        Bivio::Biz::Model::MailCollapsedList->execute_load_page
        Bivio::UI::HTML::Club::MailCollapsedList
        next=CLUB_COMMUNICATIONS_MAIL_COLLAPSED_LIST
        help=mail
    )],
    [qw(
        CLUB_COMMUNICATIONS_MAIL_COLLAPSED_DETAIL
        279
        CLUB
        MAIL_READ
        ?/mail-collapsed-msg
        Bivio::Biz::Action::PublicRealm
        Bivio::Biz::Model::MailCollapsedList->execute_load_this
        Bivio::Biz::Model::MailPartList->execute_load_all
        Bivio::UI::HTML::Club::MailDetail
        help=mail
    )],
);

__PACKAGE__->compile([
    map {($_->[0], [$_->[1]])} @_CFG
]);

=head1 METHODS

=cut

=for html <a name="get_cfg_list"></a>

=head2 static get_cfg_list() : array_ref

ONLY TO BE CALLED BY L<Bivio::Agent::Tasks>.

=cut

sub get_cfg_list {
    return \@_CFG;
}

=for html <a name="is_continuous"></a>

=head2 static is_continuous() : false

Task Ids aren't continuous.  Tasks can go away.

=cut

sub is_continuous {
    return 0;
}

#=PRIVATE METHODS

=head1 COPYRIGHT

Copyright (c) 1999,2000 bivio Inc.  All rights reserved.

=head1 VERSION

$Id$

=cut

1;
