#!perl -w
# Copyright (c) 1999 bivio, LLC.  All rights reserved.
# $Id$
use strict;

=head1 NAME

b-db-util - standard queries and dba operations

=head1 SYNOPSIS

  b-db-util count_rows
  b-db-util sql2csv file.sql [database [email]]
  b-db-util remote_sqlplus host db_login actions

  b-db-util copy_logs_to_standby
  b-db-util recover_standby
  b-db-util switch_logs_and_count_rows

=head1 DESCRIPTION

See L<Bivio::SQL::Util|Bivio::SQL::Util>.

=cut

#=IMPORTS
use Bivio::SQL::Util;

#=VARIABLES

#=PRIVATE METHODS

#=MAIN

Bivio::SQL::Util->main(@ARGV);

=head1 SEE ALSO

Bivio::SQL::Util

=head1 COPYRIGHT

Copyright (c) 1999 bivio, LLC.  All rights reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
