#!perl -w
# Copyright (c) 2002 bivio Software Artisans, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

b-db-backup - calls Bivio::SQL::Backup

=head1 RELEASE SCOPE

Societas

=head1 SYNOPSIS

b-db-backup [options] command [args...]

=head1 DESCRIPTION

See L<Bivio::SQL::Backup|Bivio::SQL::Backup>

=cut

#=IMPORTS
use Bivio::SQL::Backup;

#=VARIABLES
Bivio::SQL::Backup->main(@ARGV);

=head1 SEE ALSO

Bivio::SQL::Backup

=head1 COPYRIGHT

Copyright (c) 2002 bivio Software Artisans, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
